#!/usr/bin/env node
/* ============================================================
   AI Hub — build.
   Renders src/pages/*.js through src/layout.js into the flat
   .html files at the repo root. Zero dependencies.

       node build.js            write the pages
       node build.js --check    render and DIFF against what is
                                on disk; exit 1 if they differ
                                (nothing is written)

   --check is what makes the generated files trustworthy: it
   proves the committed HTML is exactly what the source produces,
   so nobody can hand-edit a page and have it silently survive.
   ============================================================ */
'use strict';

const fs = require('fs');
const path = require('path');
const cfg = require('./site.config.js');

/* Validate the ONE external input before any logic runs. A missing field
   would otherwise surface as a hole in a rendered page nobody looked at. */
require('./src/validate-config.js').validate(cfg);

const layout = require('./src/layout.js');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');

const BANNER = '<!-- GENERATED by build.js from src/pages/ + site.config.js — do not edit this file by hand -->';

let changed = 0, same = 0, problems = 0;

for (const page of cfg.pages) {
  const slug = page.file.replace(/\.html$/, '');
  const modPath = path.join(ROOT, 'src', 'pages', slug + '.js');

  if (!fs.existsSync(modPath)) {
    console.log(`  \x1b[31mMISSING\x1b[0m  ${page.file} is in site.config.js but src/pages/${slug}.js does not exist`);
    problems++;
    continue;
  }

  const body = require(modPath);
  if (typeof body !== 'string' || body.trim().length < 100) {
    console.log(`  \x1b[31mBAD\x1b[0m      src/pages/${slug}.js did not export page content`);
    problems++;
    continue;
  }

  const html = layout.render(page, body).replace('<html lang="en">', '<html lang="en">\n' + BANNER);
  const outPath = path.join(ROOT, page.file);
  const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null;

  if (existing === html) {
    same++;
    continue;
  }

  if (CHECK) {
    console.log(`  \x1b[31mDRIFT\x1b[0m    ${page.file} on disk differs from what the source renders`);
    problems++;
  } else {
    fs.writeFileSync(outPath, html);
    console.log(`  wrote    ${page.file.padEnd(15)} ${String(html.length).padStart(6)} bytes`);
    changed++;
  }
}

/* An orphan .html at the root is a page someone removed from the config but
   left on disk — it would still be reachable and would silently rot. */
const known = new Set(cfg.pages.map((p) => p.file));
for (const f of fs.readdirSync(ROOT)) {
  if (f.endsWith('.html') && !known.has(f)) {
    console.log(`  \x1b[31mORPHAN\x1b[0m   ${f} is not in site.config.js — delete it or add it`);
    problems++;
  }
}

console.log('');
if (problems > 0) {
  console.log(`\x1b[31mBUILD FAIL\x1b[0m  ${problems} problem(s).`);
  process.exit(1);
}
if (CHECK) {
  console.log(`\x1b[32mBUILD CHECK PASS\x1b[0m  all ${same} pages on disk match the source exactly.`);
} else {
  console.log(`\x1b[32mBUILD OK\x1b[0m  ${changed} written, ${same} unchanged.`);
}
process.exit(0);
