#!/usr/bin/env node
/* ============================================================
   AI Hub — static verification harness.
   Offline, zero dependencies. Checks CORRECTNESS, not presence.
       node verify.js
   Exits non-zero on any failure.
   ============================================================ */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const cfg = require('./site.config.js');

// Single source of truth: the page list comes from the config, so this harness
// automatically covers a page the moment it is added there.
const PAGES = cfg.pages.map((p) => p.file);
const ASSETS = ['assets/style.css', 'assets/app.js', 'assets/favicon.svg', 'assets/og.png'];
const SOURCES = ['build.js', 'site.config.js', 'src/layout.js', 'src/components.js']
  .concat(cfg.pages.map((p) => 'src/pages/' + p.file.replace(/\.html$/, '') + '.js'));

// The only external host this site is allowed to link to. Anything else is a
// finding: unverifiable links rot silently and this site preaches against that.
const ALLOWED_EXTERNAL = cfg.site.allowedExternalHosts;

let fails = 0, checks = 0;
const fail = (msg) => { fails++; console.log('  \x1b[31mFAIL\x1b[0m  ' + msg); };
const ok = () => { checks++; };
const check = (cond, msg) => { checks++; if (!cond) { fails++; checks--; console.log('  \x1b[31mFAIL\x1b[0m  ' + msg); } };
const head = (t) => console.log('\n\x1b[1m' + t + '\x1b[0m');

const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8');
const all = (re, s) => { const out = []; let m; const r = new RegExp(re.source, re.flags.includes('g') ? re.flags : re.flags + 'g'); while ((m = r.exec(s))) out.push(m); return out; };

/* ---------- 0. everything exists -------------------------------- */
head('Files');
for (const f of PAGES.concat(ASSETS).concat(SOURCES)) {
  const exists = fs.existsSync(path.join(ROOT, f));
  check(exists, `missing file: ${f}`);
  if (!exists) { console.log('\nCannot continue without all files.'); process.exit(1); }
}
console.log(`  ${PAGES.length} pages + ${ASSETS.length} assets + ${SOURCES.length} source modules present`);

/* ---------- 0a. the config itself is well-formed ----------------- */
head('Config validation');
try {
  require('./src/validate-config.js').validate(cfg);
  checks++;
  console.log('  site.config.js passes boundary validation');
} catch (e) {
  fail('site.config.js is invalid:\n' + String(e.message).split('\n').slice(1).map((l) => '        ' + l).join('\n'));
}

/* ---------- 0b. the HTML on disk IS what the source renders ------ */
head('Generated output matches source');
{
  const r = require('child_process').spawnSync(process.execPath, [path.join(ROOT, 'build.js'), '--check'],
    { cwd: ROOT, encoding: 'utf8' });
  const clean = r.status === 0;
  check(clean, 'build.js --check failed — a .html file was hand-edited, or the source changed without a rebuild:\n' +
    String(r.stdout || '').trim().split('\n').map((l) => '          ' + l).join('\n'));
  if (clean) console.log('  every .html on disk is byte-identical to what build.js renders');
}

const SRC = {};
for (const p of PAGES) SRC[p] = read(p);
const CSS = read('assets/style.css');
const JS = read('assets/app.js');

/* ---------- 1. page head hygiene -------------------------------- */
head('Page structure');
const titles = new Map();
for (const p of PAGES) {
  const s = SRC[p];
  check(/^<!doctype html>/i.test(s.trim()), `${p}: missing doctype on line 1`);
  check(/<html lang="en">/.test(s), `${p}: missing lang attribute`);
  check(/GENERATED by build\.js/.test(s), `${p}: missing the generated-file banner`);
  check(/<meta name="viewport" content="width=device-width, initial-scale=1">/.test(s), `${p}: missing/wrong viewport meta`);
  check(/<meta charset="utf-8">/.test(s), `${p}: missing charset`);

  const t = (s.match(/<title>([^<]+)<\/title>/) || [])[1];
  check(!!t, `${p}: no <title>`);
  if (t) {
    check(!titles.has(t), `${p}: duplicate <title> shared with ${titles.get(t)}`);
    titles.set(t, p);
  }
  const d = (s.match(/<meta name="description" content="([^"]+)">/) || [])[1];
  check(!!d, `${p}: no meta description`);
  if (d) check(d.length >= 60 && d.length <= 260, `${p}: meta description length ${d.length} (want 60-260)`);

  check(/<link rel="stylesheet" href="assets\/style\.css">/.test(s), `${p}: does not load the shared stylesheet`);
  check(/<script src="assets\/app\.js"><\/script>/.test(s), `${p}: does not load the shared script`);
  check((s.match(/<h1[ >]/g) || []).length === 1, `${p}: must have exactly one <h1>`);

  /* Accessibility landmarks. Six nav links precede the content on every page;
     without these a keyboard or screen-reader user walks all six every time
     (WCAG 2.4.1, Level A). */
  check(/<main id="main">/.test(s), `${p}: no <main id="main"> landmark`);
  check((s.match(/<main[ >]/g) || []).length === 1, `${p}: must have exactly one <main>`);
  check(/<a class="skip" href="#main">/.test(s), `${p}: no skip link before the nav`);
  check(s.indexOf('class="skip"') < s.indexOf('<nav'), `${p}: the skip link must come BEFORE the nav to be reachable first`);

  /* Heading order. A screen-reader user navigates by level; a jump from h2 to
     h4 breaks the outline. Every page skipped, because .card h4 was chosen for
     its size — the size now lives in CSS and the level is semantic. */
  const levels = (s.match(/<h([1-6])[ >]/g) || []).map((t) => Number(t[2]));
  const skips = [];
  for (let i = 1; i < levels.length; i++) {
    if (levels[i] - levels[i - 1] > 1) skips.push(`${levels[i - 1]}->${levels[i]}`);
  }
  check(skips.length === 0, `${p}: heading levels skip (${skips.join(', ')}) — WCAG 1.3.1`);
  check(levels[0] === 1, `${p}: first heading is h${levels[0]}, must be the h1`);

  /* Social + canonical. A page shared into Slack or WhatsApp with no card is a
     bare grey link, and this site exists to be passed around. */
  for (const tag of ['og:title', 'og:description', 'og:url', 'og:image', 'og:image:alt', 'og:type', 'og:site_name']) {
    check(new RegExp(`property="${tag}" content="[^"]+"`).test(s), `${p}: missing ${tag}`);
  }
  check(/name="twitter:card" content="summary_large_image"/.test(s), `${p}: missing twitter:card`);
  check(/<link rel="canonical" href="https:\/\/[^"]+">/.test(s), `${p}: missing canonical URL`);
  check(/<link rel="icon"/.test(s), `${p}: no favicon — every visit logs a /favicon.ico 404`);
  check(/name="theme-color"/.test(s), `${p}: no theme-color`);

  // canonical must be the pretty form used across hlur.ai, and unique per page
  const canon = (s.match(/rel="canonical" href="([^"]+)"/) || [])[1];
  if (canon) {
    check(!/\.html$/.test(canon), `${p}: canonical "${canon}" ends in .html — hlur.ai uses pretty URLs`);
    check(canon === (p === 'index.html' ? cfg.site.baseUrl + '/' : cfg.site.baseUrl + '/' + p.replace(/\.html$/, '')),
      `${p}: canonical "${canon}" does not match its own filename`);
  }
}

/* ---------- 2. shared chrome is IDENTICAL, not merely present ---- */
head('Shared chrome (nav + footer must not drift)');
const navOf = (s) => (s.match(/<nav class="nav">[\s\S]*?<\/nav>/) || [''])[0];
const footLinksOf = (s) => (s.match(/<div class="foot-links">[\s\S]*?<\/div>/) || [''])[0];

const refNav = navOf(SRC['index.html']);
check(refNav.length > 100, 'index.html: no <nav> block found');
for (const p of PAGES) {
  check(navOf(SRC[p]) === refNav, `${p}: nav block differs from index.html (twins drift — keep them byte-identical)`);
}
// every page must offer the full set of destinations in its footer
for (const p of PAGES) {
  const fl = footLinksOf(SRC[p]);
  for (const dest of PAGES) {
    if (dest === 'index.html' && p === 'index.html') continue; // index footer links out, not to itself
    /* `|| dest === 'index.html'` made this check(true) for the home link on every
       page — the link could be deleted site-wide and stay green. The footer does
       carry it, so the exemption was never needed. */
    check(fl.includes(`href="${dest}"`), `${p}: footer is missing a link to ${dest}`);
  }
}

/* ---------- 3. every link resolves (file AND anchor) ------------- */
head('Link integrity');
const idsOf = (s) => new Set(all(/\sid="([^"]+)"/g, s).map((m) => m[1]));
const IDS = {};
for (const p of PAGES) IDS[p] = idsOf(SRC[p]);

let linkCount = 0, extCount = 0;
for (const p of PAGES) {
  for (const m of all(/href="([^"]+)"/g, SRC[p])) {
    const href = m[1];
    linkCount++;
    if (/^https?:\/\//.test(href)) {
      extCount++;
      const host = href.replace(/^https?:\/\//, '').split('/')[0];
      check(ALLOWED_EXTERNAL.includes(host),
        `${p}: external link to unapproved host "${host}" (${href}) — this site does not ship links it cannot verify`);
      continue;
    }
    if (href.startsWith('mailto:')) continue;

    /* Server endpoints are routes, not files on disk — but exempting them
       blindly would let a link to a function that does not exist ship. The
       function lives in the host repo, so verify it there when that checkout
       is present, and SKIP LOUDLY when it is not (the CI case). */
    if (href.startsWith('/.netlify/functions/')) {
      const fn = href.replace('/.netlify/functions/', '').split('?')[0];
      const hostFn = path.join(ROOT, '..', 'LLC', 'Hlur_Website', 'netlify', 'functions');
      if (!fs.existsSync(hostFn)) {
        if (!global.__fnSkipNoted) {
          global.__fnSkipNoted = true;
          console.log(`  SKIP  server endpoint /${fn} — host repo not checked out here (expected in CI)`);
        }
      } else {
        const found = fs.readdirSync(hostFn).some((f) => f.replace(/\.(mjs|js|ts)$/, '') === fn);
        check(found, `${p}: links /.netlify/functions/${fn}, which does not exist in the host repo`);
      }
      continue;
    }

    const [file, frag] = href.split('#');
    const target = file || p;
    if (file) {
      check(fs.existsSync(path.join(ROOT, file)), `${p}: link to missing file "${file}"`);
    }
    if (frag) {
      const set = IDS[target];
      check(!!set, `${p}: anchor "#${frag}" points into unknown page "${target}"`);
      if (set) check(set.has(frag), `${p}: dead anchor "${href}" — no id="${frag}" in ${target}`);
    }
  }
}
console.log(`  ${linkCount} links checked (${extCount} external, all on: ${ALLOWED_EXTERNAL.join(', ')})`);

/* ---------- 4. checklists: ids unique, labels bound, COUNT CORRECT */
head('Checklists (the count must match the boxes)');
let boxTotal = 0;
const seenIds = new Set();
for (const p of PAGES) {
  const lists = all(/<ul class="checklist">[\s\S]*?<\/ul>\s*<div class="progress">[\s\S]*?<\/div>/g, SRC[p]);
  const rawLists = all(/<ul class="checklist">[\s\S]*?<\/ul>/g, SRC[p]);
  check(lists.length === rawLists.length,
    `${p}: a .checklist has no sibling .progress block after it (progress would silently never render)`);

  for (const block of lists) {
    const html = block[0];
    const boxes = all(/<input type="checkbox" id="([^"]+)">/g, html).map((m) => m[1]);
    const labels = all(/<label for="([^"]+)">/g, html).map((m) => m[1]);
    boxTotal += boxes.length;

    check(boxes.length > 0, `${p}: empty checklist block`);
    for (const id of boxes) {
      check(!seenIds.has(id), `${p}: duplicate checkbox id "${id}" — localStorage would collide across pages`);
      seenIds.add(id);
      check(labels.includes(id), `${p}: checkbox "${id}" has no <label for="${id}">`);
    }
    for (const l of labels) check(boxes.includes(l), `${p}: <label for="${l}"> has no matching checkbox`);

    const counter = (html.match(/<span data-count>([^<]*)<\/span>/) || [])[1];
    check(counter !== undefined, `${p}: progress block has no [data-count] span`);
    if (counter !== undefined) {
      const m = counter.match(/^0 of (\d+)$/);
      check(!!m, `${p}: counter text "${counter}" is not in the form "0 of N"`);
      if (m) check(Number(m[1]) === boxes.length,
        `${p}: counter says "${counter}" but the list has ${boxes.length} boxes`);
    }
    check(/<span class="bar"><i><\/i><\/span>/.test(html), `${p}: progress block missing the bar element app.js fills`);
    check(/class="reset-btn"/.test(html), `${p}: progress block missing its reset button`);
  }
}
console.log(`  ${seenIds.size} checkboxes, all uniquely id'd and labelled`);

/* ---------- 5. accordions and prompt blocks --------------------- */
head('Interactive blocks');
let accTotal = 0, promptTotal = 0;
for (const p of PAGES) {
  const accs = all(/<details class="acc"[^>]*>[\s\S]*?<\/details>/g, SRC[p]);
  accTotal += accs.length;
  for (const a of accs) {
    check(/<summary>/.test(a[0]), `${p}: a details.acc has no <summary>`);
    check(/<div class="acc-body">/.test(a[0]), `${p}: a details.acc has no .acc-body (closed-state CSS would not apply)`);
  }
  // an expand/collapse toolbar must live in a section that actually has accordions
  for (const tools of all(/<div class="acc-tools">[\s\S]*?<\/div>/g, SRC[p])) {
    check(/data-acc="open"/.test(tools[0]) && /data-acc="close"/.test(tools[0]),
      `${p}: .acc-tools missing an open or close button`);
  }
  const nTools = all(/<div class="acc-tools">/g, SRC[p]).length;
  if (nTools > 0) check(accs.length > 0, `${p}: has expand/collapse controls but no accordions`);

  const wraps = all(/<div class="prompt-wrap">[\s\S]*?<\/div>\s*<\/div>/g, SRC[p]);
  promptTotal += wraps.length;
  const nCopy = all(/class="copy-btn"/g, SRC[p]).length;
  const nWrap = all(/<div class="prompt-wrap"/g, SRC[p]).length;
  check(nCopy === nWrap, `${p}: ${nWrap} prompt-wrap blocks but ${nCopy} copy buttons`);
}
console.log(`  ${accTotal} accordions, ${promptTotal} copyable prompt blocks`);

/* ---------- 6. tag balance (cheap structural sanity) ------------ */
head('Tag balance');
for (const p of PAGES) {
  const s = SRC[p];
  for (const tag of ['section', 'details', 'table', 'ul', 'ol', 'nav', 'footer', 'summary']) {
    const open = (s.match(new RegExp('<' + tag + '[ >]', 'g')) || []).length;
    const close = (s.match(new RegExp('</' + tag + '>', 'g')) || []).length;
    check(open === close, `${p}: <${tag}> opened ${open}x but closed ${close}x`);
  }
  // every table that could overflow must sit in a scroll container
  /* /<table>/ matched nothing once the build began stamping role="table" on every
     table (src/table-labels.js), so this was check(N >= 0) and could not fail —
     the one guard whose whole job is "a wide table would break the page". */
  const tables = all(/<table[\s>]/g, s).length;
  const scrolls = all(/<div class="tscroll">/g, s).length;
  check(scrolls >= tables, `${p}: ${tables} tables but only ${scrolls} .tscroll wrappers — a wide table would break the page`);
}

/* ---------- 7. CSS invariants that bit us before ---------------- */
head('CSS invariants');
check(/\.acc:not\(\[open\]\)\s*>\s*\*:not\(summary\)\s*\{\s*display:\s*none/.test(CSS),
  'style.css: missing the closed-accordion override (a child\'s own display rule outranks the UA hiding)');

const mqIndex = CSS.indexOf('@media (max-width: 760px)');
check(mqIndex > 0, 'style.css: no mobile media query found');
// The mobile block must come AFTER every base rule it overrides — equal specificity,
// source order decides. Assert it is the last block in the file.
check(CSS.slice(mqIndex).indexOf('\n}\n') > 0 && CSS.trim().endsWith('}'),
  'style.css: mobile media query is malformed');
const afterMq = CSS.slice(mqIndex).replace(/@media[\s\S]*?\n\}/, '').trim();
check(afterMq === '', 'style.css: rules appear AFTER the mobile media query — source order will undo the mobile overrides');

check(/\.skip:focus/.test(CSS), 'style.css: the skip link never becomes visible on focus');
check(/:focus-visible/.test(CSS), 'style.css: no visible focus indicator');
/* GRADIENT BUDGET — identity, not wallpaper.
   /baseline holds itself to 19 uses for the same reason: the mark's gradient
   earns attention precisely because it is rare, and a gradient on everything is
   just a loud page. Raising this number is a decision to be argued for in the
   diff, the same way the phone-screen budget works. */
const gradUses = (CSS.match(/var\(--grad\)/g) || []).length;
check(gradUses <= 8, `style.css: the mark's gradient is used ${gradUses} times (budget 8) — identity, not wallpaper`);
/* The display gradient must never be the paint for TEXT. Its teal stop is
   2.35:1 on the light background, so clipped type would end illegibly; that is
   what --grad-text exists for. render.js measures the rendered stops; this
   catches the pairing in the source, where it is written. */
const clipRules = all(/\{[^{}]*background-clip:\s*text[^{}]*\}/g, CSS).map((m) => m[0]);
const badClip = clipRules.filter((r) => /var\(--grad\)/.test(r));
check(badClip.length === 0, 'style.css: --grad is clipped to text somewhere — use --grad-text (the display gradient ends at 2.35:1)');

check(/prefers-reduced-motion/.test(CSS), 'style.css: does not honour prefers-reduced-motion');
for (const v of ['--bg', '--surface', '--text', '--green', '--red', '--amber', '--blue', '--radius']) {
  check(CSS.includes(v + ':'), `style.css: theme token ${v} not defined`);
}
check(/@media \(prefers-color-scheme: dark\)/.test(CSS), 'style.css: no dark mode block');
// the dark block must redefine every token the light block defines
const lightBlock = (CSS.match(/:root \{[\s\S]*?\n\}/) || [''])[0];
const darkBlock = (CSS.match(/@media \(prefers-color-scheme: dark\) \{[\s\S]*?\n  \}/) || [''])[0];
const tokensOf = (b) => new Set(all(/(--[a-z0-9-]+):/g, b).map((m) => m[1]));
const lightTokens = tokensOf(lightBlock), darkTokens = tokensOf(darkBlock);
/* A token whose value is BUILT from other tokens follows the theme on its own —
   custom properties resolve at use time, so --grad: linear-gradient(var(--g1)…)
   already paints the dark stops once --g1 is redefined. Verified in both themes
   before this exemption was added; requiring it to be restated in the dark block
   would mean maintaining the same gradient twice, which is how the two drift. */
const composed = new Set(
  all(/(--[a-z0-9-]+):\s*([^;]*)/g, lightBlock)
    .filter((m) => m[2].includes('var(--'))
    .map((m) => m[1])
);
const colourish = [...lightTokens].filter(
  (t) => !['--radius', '--radius-sm', '--wrap', '--pad'].includes(t) && !composed.has(t)
);
for (const t of colourish) {
  check(darkTokens.has(t), `style.css: ${t} has no dark-mode value — it will render a light colour on a dark background`);
}

// nav padding must equal content padding or the logo misaligns with the content
check(/\.nav-inner\s*\{[^}]*padding:\s*10px var\(--pad\)/.test(CSS),
  'style.css: .nav-inner must use var(--pad) horizontally so the brand aligns with page content');
check(/\.wrap\s*\{[^}]*padding:\s*0 var\(--pad\)/.test(CSS),
  'style.css: .wrap must use var(--pad) horizontally');

/* ---------- 8. every CSS class used in HTML actually exists ------ */
head('Class coverage');
const cssClasses = new Set(all(/\.([a-z][a-z0-9-]*)/g, CSS).map((m) => m[1]));
const usedClasses = new Set();
for (const p of PAGES) {
  for (const m of all(/class="([^"]+)"/g, SRC[p])) {
    m[1].split(/\s+/).filter(Boolean).forEach((c) => usedClasses.add(c));
  }
}
const orphans = [...usedClasses].filter((c) => !cssClasses.has(c));
check(orphans.length === 0, `HTML uses classes with no CSS rule: ${orphans.join(', ')}`);

/* ---------- 9. JS wires everything the HTML declares ------------- */
head('JS / HTML contract');
for (const hook of ['.acc-tools', 'data-acc', '.checklist', 'data-count', '.bar > i', '.reset-btn', '.prompt-wrap', '.copy-btn', '.nav-links a']) {
  check(JS.includes(hook), `app.js: never references "${hook}" that the HTML depends on`);
}
/* Brace-match every try block and assert each localStorage access falls
   inside one. The old test was /try\s*\{[\s\S]*?localStorage/ — an unbounded
   lazy gap, so a single unrelated `try {` anywhere in the file satisfied it.
   Stripping every real try/catch and leaving one decoy passed. */
{
  // comments mention localStorage; only real code counts
  const JSC = JS.replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
                .replace(/^\s*\/\/.*$/gm, (m) => m.replace(/[^\n]/g, ' '));
  const ranges = [];
  for (let i = JSC.indexOf('try'); i !== -1; i = JSC.indexOf('try', i + 1)) {
    const open = JSC.indexOf('{', i);
    if (open === -1 || !/^try\s*$/.test(JSC.slice(i, open))) continue;
    let depth = 0, j = open;
    for (; j < JSC.length; j++) {
      if (JSC[j] === '{') depth++;
      else if (JSC[j] === '}') { depth--; if (depth === 0) break; }
    }
    ranges.push([open, j]);
  }
  const unguarded = [];
  for (let i = JSC.indexOf('localStorage'); i !== -1; i = JSC.indexOf('localStorage', i + 1)) {
    if (!ranges.some(([a, b]) => i > a && i < b)) {
      unguarded.push(JSC.slice(Math.max(0, i - 30), i + 40).replace(/\s+/g, ' ').trim());
    }
  }
  check(unguarded.length === 0,
    `app.js: ${unguarded.length} localStorage access(es) outside any try block — private browsing throws there: ${unguarded.slice(0, 2).join(' | ')}`);
}
check(/aria-current/.test(JS), 'app.js: does not mark the current nav item');

/* ---------- 10. content hygiene --------------------------------- */
head('Content hygiene');
// Assembled from fragments so this guard file never contains the literals it
// hunts for — otherwise the repo-wide sweep below would flag itself.
const BANNED = [
  'TO' + 'DO', 'FIX' + 'ME', 'Lorem ' + 'ipsum', 'X' + 'XX', 'PLACE' + 'HOLDER',
  'unde' + 'fined', 'Na' + 'N', '[object ' + 'Object]', 'null' + 'null',
];
for (const p of PAGES) {
  for (const b of BANNED) {
    check(!SRC[p].includes(b), `${p}: contains placeholder/leak marker "${b}"`);
  }
  // the site's own honesty rule: every page carries the date it was written
  check(SRC[p].includes(cfg.site.written),
    `${p}: does not carry the site date "${cfg.site.written}" from site.config.js — this site requires its own claims to be dated`);
}

// Attribution: the one borrowed term must be credited on the page that uses it.
/* Every page footer promises "where an idea came from someone else, it is named".
   These are the borrowed terms; each must carry its credit on the page that uses it.
   A term that loses its attribution in an edit is a plagiarism regression, so it
   fails the build rather than being caught by a reader. */
const BORROWED = [
  { term: /jagged/i, credit: /Dell'Acqua/, who: "Dell'Acqua et al. (HBS working paper, 2023)" },
  { term: /pre-mortem/i, credit: /Gary Klein/, who: 'Gary Klein (Harvard Business Review, 2007)' },
];
let attributed = 0;
for (const b of BORROWED) {
  const users = PAGES.filter((p) => b.term.test(SRC[p]));
  for (const p of users) {
    check(b.credit.test(SRC[p]), `${p}: uses a borrowed term without crediting ${b.who}`);
  }
  attributed += users.length;
}
console.log(`  ${attributed} page-uses of a borrowed term; all attributed`);

// No product names, prices or model versions — the site promises it has none.
// Prices need a currency or a rate next to a NUMBER — a bare "per month" is a
// duration, not a price, and flagging it was a false positive on first run.
const PRODUCT_CLAIMS = /[$£€]\s?\d|\d+\s*(?:USD|EUR|GBP|dollars|pounds|euros)|\d+\s*(?:\/|per )\s*(?:mo\b|month|seat|user)|\bGPT-?\d|\bClaude \d|\bGemini \d|\bLlama \d|\bo\d-mini\b/;
for (const p of PAGES) {
  const body = SRC[p].replace(/<!--[\s\S]*?-->/g, '');
  check(!PRODUCT_CLAIMS.test(body),
    `${p}: contains a price or model version number — this site promises none, because they rot`);
}

/* ---------- 11. front door reaches every track ------------------ */
head('Navigation completeness');
const idx = SRC['index.html'];
for (const p of PAGES.filter((x) => x !== 'index.html')) {
  check(new RegExp(`class="track" href="${p}"`).test(idx), `index.html: no track card links to ${p}`);
}
// every non-index page must have a pager back to somewhere
for (const p of PAGES.filter((x) => x !== 'index.html')) {
  check(/<div class="pager">/.test(SRC[p]), `${p}: no next/prev pager — reader hits a dead end`);
}
// the six named problems on the front door must map to the five tracks + foundations
{
  // scoped to the grid the message names, and not limited to 01-09
  const probSection = (idx.match(/<section id="problem">[\s\S]*?<\/section>/) || [''])[0];
  const numbered = (probSection.match(/<span class="num">\d+<\/span>/g) || []).length;
  check(numbered === 6, `index.html: the "problem, named" grid has ${numbered} numbered cards, expected 6`);
}

/* ---------- 11b. public-release requirements --------------------- */
head('Public-release requirements');
{
  // This repo is published. A missing licence makes every "steal this" on the
  // site legally false, and it is the kind of thing nobody notices is absent.
  const hasLicense = fs.existsSync(path.join(ROOT, 'LICENSE'));
  check(hasLicense, 'no LICENSE file — the site invites reuse ("Steal these", "ours to copy freely") while granting none');
  if (hasLicense) {
    const lic = read('LICENSE');
    check(/MIT/.test(lic), 'LICENSE does not name a code licence');
    check(/CC BY 4\.0/.test(lic), 'LICENSE does not name a content licence');
    check(/not medical, legal, financial/i.test(lic) || /not medical, legal or financial/i.test(lic),
      'LICENSE carries no not-professional-advice disclaimer');
  }
  const rm = read('README.md');
  check(/\[LICENSE\]\(LICENSE\)/.test(rm), 'README does not link the LICENSE');
  /* The README claimed "1,979 checks" while the harnesses ran 2,190 — a stale
     rigour claim in the one document strangers read first. Totals live in the
     harness output, never in prose. Named per-suite floors are allowed only in
     the selfcheck section that documents the floors themselves. */
  check(!/\*\*[0-9][0-9,]* checks?\*\*/.test(rm),
    'README states an exact check total — it will rot; point at selfcheck output instead');
  check(!/Not deployed anywhere/.test(rm), 'README still claims the site is not deployed');
  check(!/thoughts\.rtf/.test(rm), 'README still points readers at the private notes file');
  check(!fs.existsSync(path.join(ROOT, '.git')) ||
        require('child_process').spawnSync('git', ['ls-files', 'thoughts.rtf'], { cwd: ROOT, encoding: 'utf8' }).stdout.trim() === '',
    'thoughts.rtf is still tracked by git — it would publish');
  check(/\.claude\//.test(read('.gitignore')), '.gitignore does not exclude .claude/ (it holds absolute local paths)');
  console.log('  licence present, private notes untracked, README clean');
}

/* ---------- 11c. counting must stay disclosed and honest --------- */
head('Usage counting');
{
  const hasTally = /function tally\(/.test(JS);
  if (!hasTally) {
    checks++;
    console.log('  no tally() in app.js — nothing to disclose');
  } else {
    /* A counter plus a "no tracking" claim is the exact shape of the dishonesty
       this site warns readers about. If the code counts, the footer says so. */
    for (const p of PAGES) {
      check(!/No tracking, no cookies/.test(SRC[p]),
        `${p}: still claims "No tracking" while app.js counts page views`);
      check(/counts six things and nothing else/.test(SRC[p]),
        `${p}: app.js counts, but this page does not disclose what is counted`);
      check(/tally\?site=hub/.test(SRC[p]),
        `${p}: the disclosure does not link the public numbers`);
    }
    // every event the code can send must be named in the disclosure
    const named = ['page view', 'scroll', 'copied prompt', 'ticked box'];
    for (const n of named) {
      check(SRC['index.html'].includes(n),
        `the disclosure does not mention "${n}" — it must name every event tally() can send`);
    }
    // and the code must stay gated + allowlisted
    check(/location\.hostname !== 'hlur\.ai'/.test(JS),
      'app.js: tally is not host-gated — a fork or a local file would phone home');
    check(/TALLY\.indexOf/.test(JS), 'app.js: tally does not check its own allowlist');
    check(/catch \(e\) \{ \/\* never let counting break anything \*\/ \}/.test(JS),
      'app.js: tally is not wrapped to fail soft');
    /* EVERY NAME THE CLIENT CAN SEND MUST BE ON THE SERVER'S LIST.
       This is the check that was missing. The client derives its event name from
       the URL slug, the live front door is /hub/, so it sent "hub:load" — and the
       server allowlist only had "index:load", so every arrival at the entry page
       was silently discarded from the day counting began. Neither side was wrong
       on its own; they simply never agreed, and nothing compared them. Tally is
       host-gated to hlur.ai, so no rendered test can exercise the send path —
       this static cross-check is the only place the two lists can be reconciled.
       Skips loudly when the host repo is not checked out (the CI case). */
    const hostTally = path.join(ROOT, '..', 'LLC', 'Hlur_Website', 'netlify', 'functions', 'tally.mjs');
    if (!fs.existsSync(hostTally)) {
      console.log('  SKIP  tally event names — host repo not checked out here (expected in CI)');
    } else {
      const server = new Set(
        (fs.readFileSync(hostTally, 'utf8').match(/hub:\s*\{[\s\S]*?events:\s*\[([\s\S]*?)\]/) || [, ''])[1]
          .match(/'([^']+)'/g)?.map((x) => x.slice(1, -1)) || []
      );
      const appSrc = fs.readFileSync(path.join(ROOT, 'assets', 'app.js'), 'utf8');
      const suffixes = (appSrc.match(/var TALLY = \[([^\]]*)\]/) || [, ''])[1]
        .match(/'([^']+)'/g)?.map((x) => x.slice(1, -1)) || [];
      const slugs = cfg.pages.map((pg) => pg.file.replace(/\.html$/, ''));
      const canSend = [];
      for (const sl of slugs) for (const suf of ['load', 'deep']) if (suffixes.includes(suf)) canSend.push(`${sl}:${suf}`);
      for (const suf of suffixes) if (!['load', 'deep'].includes(suf)) canSend.push(suf);
      check(server.size > 0, 'could not read the hub event allowlist out of the host tally function');
      const orphans = canSend.filter((e) => !server.has(e));
      check(orphans.length === 0,
        `app.js can send ${orphans.join(', ')} but the server allowlist drops them — those visits are never counted`);
    }

    console.log('  counting is disclosed, event-named, host-gated and fail-soft');
  }
}

/* ---------- 12. repo-wide leak sweep ----------------------------- */
head('Repo-wide sweep');
{
  // .sh added 2026-08-08: sync_hlur.sh hard-coded an absolute home path and the
  // sweep never looked at shell scripts — the one file type that holds deploy
  // paths by nature. Found one step before this repo was made public.
  const TEXTY = /\.(html|css|js|md|json|csv|txt|svg|sh|ya?ml)$/;

  /* ASK GIT WHAT IS PUBLISHED, do not guess by filename.
     The walk this replaces skipped every dot-entry, so .github/ was never
     entered and the workflows went unswept — the same blind spot the .sh line
     above was written for. Widening it to dot-dirs then swept .claude/, which
     is gitignored and local-only, and produced a false leak on the first run.
     Tracked-by-git IS the definition of "would be published", so use it: it
     admits .github/ and the extensionless scripts (selfcheck, hooks/pre-commit)
     and excludes everything ignored, with no list to keep up to date. */
  const isScript = (f) => {
    if (path.extname(f)) return false;
    try { return fs.readFileSync(path.join(ROOT, f), 'utf8').startsWith('#!'); } catch (e) { return false; }
  };

  let files;
  try {
    const tracked = require('child_process').execSync('git ls-files -z', { cwd: ROOT, maxBuffer: 1 << 24 })
      .toString().split('\0').filter(Boolean);
    if (!tracked.length) throw new Error('git ls-files returned nothing');
    files = tracked.filter((f) => TEXTY.test(f) || isScript(f)).map((f) => path.join(ROOT, f));
  } catch (e) {
    // FAIL CLOSED: a guard that cannot read the tree must block, not pass.
    files = null;
    fail(`repo sweep could not read the tree (${e.message}) — treating as a failure, not a pass`);
  }

  if (files) {
    // this harness and the test suite legitimately contain the markers as data
    const SELF = new Set([path.join(ROOT, 'verify.js'), path.join(ROOT, 'test.js')]);

    /* PUBLICATION LEAKS. This repo is public, so anything identifying the
       author's machine, other private projects, or credentials must not ship.
       The earlier sweep looked ONLY for placeholder markers and reported
       "23 text files swept, no leak markers" while render.js contained an
       absolute /Users/<name>/... path that also named an unrelated private
       project. Patterns are assembled from fragments so this file does not
       trip its own sweep. */
    const LEAKS = [
      { name: 'absolute macOS home path', re: new RegExp('/' + 'Users' + '/[A-Za-z0-9._-]+/') },
      { name: 'absolute Linux home path', re: new RegExp('/' + 'home' + '/[A-Za-z0-9._-]+/') },
      { name: 'absolute Windows home path', re: new RegExp('C:' + '\\\\Users\\\\[A-Za-z0-9._-]+') },
      { name: 'email address', re: /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/ },
      { name: 'API-key-shaped string', re: new RegExp('(' + 'sk' + '-[A-Za-z0-9]{16}|' + 'ghp' + '_[A-Za-z0-9]{20}|' + 'AKIA' + '[A-Z0-9]{12})') },
      /* Only a defect in something that SHIPS. render.js binds a throwaway
         localhost server to serve the pages the way the host does — that is a
         test fixture, not a leak. Paths, emails and keys identify the author
         wherever they appear; a loopback URL only matters in shipped output. */
      { name: 'localhost or private-network URL', re: /https?:\/\/(localhost|127\.0\.0\.1|192\.168\.)/, shippedOnly: true },
    ];
    const SHIPPED = (f) => /\.html$/.test(f) || /[\\/]assets[\\/]/.test(f);

    let hits = 0;
    for (const f of files) {
      if (SELF.has(f)) continue;
      const body = fs.readFileSync(f, 'utf8');
      /* Value markers are leaks only in RENDERED output. In .js they are
         ordinary JavaScript (`if (x === undefined)`), and in .md the docs
         legitimately name them when describing this very guard. Scoping them
         to .html is the honest rule; the alternative is widening an exemption
         list until the guard means nothing. Placeholder markers
         (TODO/FIXME/lorem) still apply everywhere. */
      const rendered = /\.html$/.test(f);
      const RENDERED_ONLY = new Set(['unde' + 'fined', 'Na' + 'N', '[object ' + 'Object]', 'null' + 'null']);
      for (const b of BANNED) {
        if (!rendered && RENDERED_ONLY.has(b)) continue;
        if (body.includes(b)) {
          fail(`${path.relative(ROOT, f)}: contains leak marker "${b}"`);
          hits++;
        }
      }
      for (const L of LEAKS) {
        if (L.shippedOnly && !SHIPPED(f)) continue;
        const m = L.re.exec(body);
        if (m) {
          const line = body.slice(0, m.index).split('\n').length;
          fail(`${path.relative(ROOT, f)}:${line}: ${L.name} would be published — "${m[0].slice(0, 60)}"`);
          hits++;
        }
      }
    }
    if (hits === 0) { checks++; console.log(`  ${files.length} text files swept: no placeholders, paths, emails, keys or private hosts`); }
  }
}

/* ---------- summary --------------------------------------------- */
console.log('\n' + '='.repeat(58));
if (fails === 0) {
  console.log(`\x1b[32mPASS\x1b[0m  ${checks} checks, 0 failures.`);
  console.log(`      ${PAGES.length} pages · ${seenIds.size} checkboxes · ${accTotal} accordions · ${linkCount} links`);
  process.exit(0);
} else {
  console.log(`\x1b[31mFAIL\x1b[0m  ${fails} failure(s) out of ${checks + fails} checks.`);
  process.exit(1);
}
