/* AI Hub — content for further.html
   The shell (head, nav, hero, pager, footer) is generated by src/layout.js
   from site.config.js. This file is ONLY the body content. */
'use strict';

module.exports = `<!-- ============================================================ -->
<section id="ladders">
  <div class="wrap">
    <p class="slabel">Pick your road</p>
    <h2>Three roads, with real price tags</h2>

    <figure class="fig">
      <svg viewBox="0 0 380 175" role="img" aria-label="Diagram: three roads of increasing length from a single starting point — everyday user in about a month, the person at work in months, builder or founder in a year or more">
        <circle cx="30" cy="88" r="9" fill="var(--green)"/>
        <text x="30" y="115" text-anchor="middle" font-size="12" fill="var(--text-sec)">start</text>
        <path d="M40 84 C 80 60, 110 48, 148 42"  stroke="var(--green)" stroke-width="2.4" fill="none" stroke-linecap="round"/>
        <path d="M40 88 C 110 84, 180 80, 252 74" stroke="var(--text-sec)" stroke-width="2.2" fill="none" stroke-linecap="round" stroke-dasharray="7 5"/>
        <path d="M40 92 C 130 116, 250 132, 352 128" stroke="var(--text-ter)" stroke-width="2" fill="none" stroke-linecap="round" stroke-dasharray="2 5"/>
        <circle cx="148" cy="42" r="5.5" fill="var(--green)"/>
        <circle cx="252" cy="74" r="5.5" fill="var(--text-sec)"/>
        <circle cx="352" cy="128" r="5.5" fill="var(--text-ter)"/>
        <text x="152" y="26" text-anchor="middle" font-size="12" font-weight="620" fill="var(--text)">A · everyday user</text>
        <text x="152" y="60" text-anchor="middle" font-size="12" fill="var(--text-ter)">~a month</text>
        <text x="256" y="58" text-anchor="middle" font-size="12" font-weight="620" fill="var(--text)">B · at work</text>
        <text x="256" y="94" text-anchor="middle" font-size="12" fill="var(--text-ter)">months</text>
        <text x="330" y="152" text-anchor="middle" font-size="12" font-weight="620" fill="var(--text)">C · builder</text>
        <text x="330" y="168" text-anchor="middle" font-size="12" fill="var(--text-ter)">a year or more</text>
      </svg>
      <figcaption>Every road shares the first mile: fluency plus the checking habit.</figcaption>
    </figure>

    <div class="grid grid-3">
      <div class="card">
        <span class="num">Road A</span>
        <h3>Confident everyday user</h3>
        <p class="small muted">Uses it naturally for life admin, learning, writing and thinking. Knows what it's bad at. Checks without being told.</p>
        <p class="small"><strong>Cost:</strong> ~20 min/day for a month.<br><strong>Reachable by:</strong> anyone. No technical background at all.</p>
      </div>
      <div class="card">
        <span class="num">Road B</span>
        <h3>The person at work who gets it</h3>
        <p class="small muted">Has rebuilt a real part of their own job around it, can show the before-and-after, and is trusted to advise colleagues.</p>
        <p class="small"><strong>Cost:</strong> Road A, then 3–6 months of applying it to real work.<br><strong>Reachable by:</strong> anyone with a job that involves words, numbers or process.</p>
      </div>
      <div class="card">
        <span class="num">Road C</span>
        <h3>Builder or founder</h3>
        <p class="small muted">Builds tools or a product on top of AI. Understands cost per use, reliability, and what stops a competitor copying it.</p>
        <p class="small"><strong>Cost:</strong> 6–24 months, real money, real risk.<br><strong>Reachable by:</strong> fewer people than the internet implies. Read the honest section below first.</p>
      </div>
    </div>

    <div class="note note-info">
      <span class="nlabel">Nobody skips A</span>
      <p>Every road starts with fluency and the checking habit. A founder who can't tell a
      good answer from a plausible one will build a product that confidently ships wrong
      answers to customers — which is the most common way these things fail.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="thirty">
  <div class="wrap">
    <p class="slabel">Road A</p>
    <h2>Four weeks, twenty minutes a day</h2>
    <p class="lead">
      One job per week, five things in each. Tick as you go — saved on this device.
    </p>

    <div class="wk-deck"><div class="wk"><h3>Week 1 · Fluency — get comfortable</h3>
    <div class="card">
      <ul class="checklist">
        <li><input type="checkbox" id="d1"><label for="d1">Read <a href="index.html#sixty">the short version</a> and the <a href="https://hlur.ai/baseline">foundations guide</a>. Nothing else.</label></li>
        <li><input type="checkbox" id="d2"><label for="d2">Ask it to explain something you've never understood — three times, each simpler.</label></li>
        <li><input type="checkbox" id="d3"><label for="d3">Paste a real document (letter, contract, form) and ask what it means for you.</label></li>
        <li><input type="checkbox" id="d4"><label for="d4">Take one answer through five rounds of "that's not right because…" and watch it improve.</label></li>
        <li><input type="checkbox" id="d5"><label for="d5">Deliberately break it: push one task until the answers go wrong. Notice where the edge was.</label></li>
      </ul>
      <div class="progress"><span data-count>0 of 5</span><span class="bar"><i></i></span><button type="button" class="reset-btn">reset</button></div>
    </div></div>

    <div class="wk"><h3>Week 2 · Your own life — make it useful</h3>
    <div class="card">
      <ul class="checklist">
        <li><input type="checkbox" id="d6"><label for="d6">Start a friction log: one line every time something is tedious. Keep it all week.</label></li>
        <li><input type="checkbox" id="d7"><label for="d7">Work through the <a href="map.html#audit">sixteen-item self-audit</a> and try three you'd never considered.</label></li>
        <li><input type="checkbox" id="d8"><label for="d8">Use it as a tutor for something you actually want to learn — quizzing you, not lecturing.</label></li>
        <li><input type="checkbox" id="d9"><label for="d9">Rehearse a real conversation you're dreading, with it playing the other person.</label></li>
        <li><input type="checkbox" id="d10"><label for="d10">Pick the worst item in your friction log and hand it over properly, with the real material.</label></li>
      </ul>
      <div class="progress"><span data-count>0 of 5</span><span class="bar"><i></i></span><button type="button" class="reset-btn">reset</button></div>
    </div></div>

    <div class="wk"><h3>Week 3 · Checking — the week that earns the trust</h3>
    <div class="card">
      <ul class="checklist">
        <li><input type="checkbox" id="d11"><label for="d11">Run the <a href="trust.html#moves">calibration test</a>: ask about your own area of expertise and count the errors.</label></li>
        <li><input type="checkbox" id="d12"><label for="d12">Ask for sources on something and open every one. Note how many hold up.</label></li>
        <li><input type="checkbox" id="d13"><label for="d13">Give one real task to two different AI products and compare where they disagree.</label></li>
        <li><input type="checkbox" id="d14"><label for="d14">Take an answer you liked and make it argue against itself. Read the critique properly.</label></li>
        <li><input type="checkbox" id="d15"><label for="d15">Run the <a href="trust.html#checklist">one-page check</a> on something real before you send it.</label></li>
      </ul>
      <div class="progress"><span data-count>0 of 5</span><span class="bar"><i></i></span><button type="button" class="reset-btn">reset</button></div>
    </div></div>

    <div class="wk"><h3>Week 4 · Make something — proof it's real</h3>
    <div class="card">
      <ul class="checklist">
        <li><input type="checkbox" id="d16"><label for="d16">Build your own <a href="tools.html#bench">five-prompt test</a> and run it on two products.</label></li>
        <li><input type="checkbox" id="d17"><label for="d17">Make one small thing you'd otherwise not have made: a spreadsheet formula, a script, a one-page site, a plan.</label></li>
        <li><input type="checkbox" id="d18"><label for="d18">Rebuild one recurring task in your week around it, and time yourself before and after.</label></li>
        <li><input type="checkbox" id="d19"><label for="d19">Teach one person one thing from this hub. Teaching is where you find out what you actually know.</label></li>
        <li><input type="checkbox" id="d20"><label for="d20">Write five lines: what it's genuinely good at for <em>you</em>, and what you'll never trust it with.</label></li>
      </ul>
      <div class="progress"><span data-count>0 of 5</span><span class="bar"><i></i></span><button type="button" class="reset-btn">reset</button></div>
    </div></div></div>

    <!-- Sits AFTER the deck, not inside it: as a fifth child it became a fifth
         swipe card on a phone — a note shaped like a week that isn't one, and a
         fifth progress dot for four weeks. It closes the deck, so it belongs
         under it, below the dots. -->
    <div class="note note-do">
      <span class="nlabel">The end of week 4</span>
      <p>That last item is the deliverable. Anyone who can write those five lines from
      their own experience is no longer guessing in the dark — and is ahead of most people
      currently being told to embrace AI.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="work">
  <div class="wrap">
    <p class="slabel">Road B</p>
    <h2>Finding the AI-shaped work in your actual job</h2>
    <p class="lead">
      Your employer said "use AI" and stopped there. Here is the rest.
    </p>

    <h3>The four task types worth handing over first</h3>
    <div class="tscroll">
      <table>
        <thead><tr><th style="width:26%">Type</th><th>Looks like</th><th>Why it's first</th></tr></thead>
        <tbody>
          <tr><td><strong>Reformatting</strong></td><td>Notes → minutes. Data → report. Long → short. One template → another.</td><td>The answer is already in what you supply, so there's little to invent and it's easy to check.</td></tr>
          <tr><td><strong>First drafts</strong></td><td>Anything you currently stare at a blank page for.</td><td>You were always going to rewrite it. The AI's mediocrity costs nothing.</td></tr>
          <tr><td><strong>Reading piles</strong></td><td>Long documents, many emails, transcripts, feedback, applications.</td><td>Volume is exactly where humans get expensive and inattentive.</td></tr>
          <tr><td><strong>Rehearsal and review</strong></td><td>Practising the pitch, pre-mortems (Gary Klein's technique — imagine it has already failed, then explain how), "what will they object to?"</td><td>Zero risk, and nobody else's time is spent.</td></tr>
        </tbody>
      </table>
    </div>

    <div class="note note-dont">
      <span class="nlabel">Don't automate what you don't understand</span>
      <p>If you can't do the task yourself, you can't tell when the AI does it wrong — so
      you've automated a step you can no longer supervise. Start where you're competent.
      Expand outward as your checking improves, not as your confidence does.</p>
    </div>

    <h3>How to propose it without it going badly</h3>
    <ol class="steps">
      <li><h3>Check the rules first — before anything else</h3>
        <p class="muted">Which tools are approved, what data is allowed in them, and whether
        clients or patients must be told. Do this <em>first</em>. Quiet use of an unapproved
        tool on real work can already be a policy breach or a data leak — and in law,
        medicine, accounting and finance, confidentiality duties are obligations, not
        preferences. Getting this wrong is also the fastest way to get AI banned for everyone.</p>
        <p class="muted"><strong>If your company has no rules yet</strong> — an "embrace AI"
        announcement and nothing else — that is not permission, it is a gap. Ask the person
        who owns data or IT, in writing, one narrow question: "Is there an approved tool for
        this? If not, may I use [tool] on non-confidential work while we decide?" You get an
        answer or you get on record asking — both protect you. In a company with no policy,
        the person who asks the question in writing often ends up shaping the policy.</p></li>
      <li><h3>Then prove it on your own work</h3>
        <p class="muted">One task, one month, timed before and after. An unarguable
        before-and-after beats any amount of enthusiasm.</p></li>
      <li><h3>Lead with the checking, not the speed</h3>
        <p class="muted">"Here's how I verify the output" is what makes managers comfortable.
        "It's so fast" is what makes them nervous.</p></li>
      <li><h3>Give away the method</h3>
        <p class="muted">Hoarding it buys you a few months. Teaching it makes you the person
        the organisation asks — which is worth considerably more, for longer.</p></li>
    </ol>
  </div>
</section>

<!-- ============================================================ -->
<section id="careers">
  <div class="wrap">
    <p class="slabel">The uncomfortable part</p>
    <h2>What this honestly does to your job</h2>
    <p>
      Nobody knows how this lands in ten years, and anyone who says they do is selling
      something. The direction of travel is visible enough to plan around.
    </p>

    <div class="grid grid-2">
      <div class="card">
        <h3>Getting less valuable</h3>
        <ul class="clean no small" style="margin-top:8px">
          <li>Producing competent first drafts</li>
          <li>Formatting, tidying, transcribing</li>
          <li>Knowing facts others could look up</li>
          <li>Routine boilerplate of any kind</li>
          <li>Being the only person who can operate the tool</li>
        </ul>
      </div>
      <div class="card">
        <h3>Getting more valuable</h3>
        <ul class="clean yes small" style="margin-top:8px">
          <li>Knowing which question is worth asking</li>
          <li>Telling a good answer from a plausible one</li>
          <li>Deep domain knowledge — the thing that lets you check</li>
          <li>Taste, judgement, and taking responsibility</li>
          <li>Everything physical, relational, or requiring accountability</li>
        </ul>
      </div>
    </div>

    <div class="note note-warn">
      <span class="nlabel">The bit people skip past</span>
      <p>Every skill in the right-hand column is built by doing the work in the left-hand
      column for years. If juniors never write the bad first draft, the pipeline that
      produces the judgement stops. If you're early in a career, use AI to go
      <em>further</em>, not to skip the part where you learn to tell good from bad — that
      part is the career.</p>
    </div>

    <p style="margin-top:18px">
      The reasonable expectation isn't "AI takes your job" or "nothing changes." It's that
      the mix inside your job shifts, faster in some fields than others, and that the people
      who stay useful are the ones who moved deliberately rather than waiting to be told.
      Which is what the previous four pages were for.
    </p>
  </div>
</section>

<!-- ============================================================ -->
<section id="startup">
  <div class="wrap">
    <p class="slabel">Road C</p>
    <h2>Starting an AI company, with the awkward parts included</h2>
    <p class="lead">
      It has never been cheaper to build a working product. That is exactly why building
      one is no longer the hard part — and why most of the advice you'll see is optimistic
      in the wrong places.
    </p>

    <div class="acc-tools">
      <button type="button" data-acc="open">Expand all</button>
      <button type="button" data-acc="close">Collapse all</button>
    </div>

    <div class="acc-deck">
      <details class="acc" open>
        <summary><span class="sq">01</span>A thin wrapper around a model is not a business</summary>
        <div class="acc-body">
          <p>If your product is a text box that passes the request to someone else's model
          with a clever instruction attached, then a competitor rebuilds it in a weekend, and
          the model provider may ship it as a feature for free. That's not a reason not to
          start — it's a reason not to stop there.</p>
          <p><strong>What actually holds:</strong> access to data nobody else has; a workflow
          so deep in a specific job that switching is painful; distribution and trust in a
          market that's hard to enter; being the one who carries the regulatory or liability
          burden customers won't carry themselves.</p>
        </div>
      </details>

      <details class="acc">
        <summary><span class="sq">02</span>Every use costs you money — this isn't normal software</summary>
        <div class="acc-body">
          <p>Traditional software has near-zero cost per extra user. AI products don't:
          every answer burns computation you pay for. A free tier can lose money on your most
          enthusiastic users, and the heaviest users are often the ones you most wanted.</p>
          <p><strong>Work out early:</strong> what one typical customer costs you per month to
          serve, and what happens to that number if they use it ten times more than you assumed.
          Do this before you price anything, not after.</p>
        </div>
      </details>

      <details class="acc">
        <summary><span class="sq">03</span>The demo is the easy part</summary>
        <div class="acc-body">
          <p>An impressive demo can take a weekend. Almost all of the remaining work is what
          happens when it's wrong in front of a paying customer: how you detect it, how the
          product behaves, who's accountable, what you promise, and how you improve it without
          breaking what already worked.</p>
          <p class="small muted">Teams routinely underestimate that second part, because the
          demo felt like the product.</p>
        </div>
      </details>

      <details class="acc">
        <summary><span class="sq">04</span>Do it manually for five customers first</summary>
        <div class="acc-body">
          <p>The cheapest validation there is. Find five people with the problem and solve it
          by hand — you, an AI chat window, and an afternoon each. No product, no code.</p>
          <ul>
            <li>If nobody will let you do it free, they won't pay for the automated version.</li>
            <li>Doing it by hand teaches you the actual workflow, including the messy parts that would have broken your design.</li>
            <li>You find out what "good enough to be trusted" means in that job — which is the number your whole product has to hit.</li>
          </ul>
        </div>
      </details>

      <details class="acc">
        <summary><span class="sq">05</span>Build on shifting ground, deliberately</summary>
        <div class="acc-body">
          <p>Models, prices and capabilities change on a timescale of months. Two consequences
          worth designing for from day one:</p>
          <ul>
            <li><strong>Don't marry one provider.</strong> Keep the model swappable, and keep your own set of test cases so you can tell whether a swap actually improved anything.</li>
            <li><strong>Assume the base models get better.</strong> If your entire value is a gap in the current model's ability, the next release may close it. Build where improvement helps you rather than erases you.</li>
          </ul>
        </div>
      </details>

      <details class="acc">
        <summary><span class="sq">06</span>You are accountable for what it outputs</summary>
        <div class="acc-body">
          <p>"The model said it" is not a defence to a customer, a regulator or a court. If
          your product gives advice, handles money, touches health, or makes decisions about
          people, get real advice about your obligations before you launch, not after.</p>
          <p class="small muted">It is also, incidentally, hard to copy. Being the company
          willing and able to stand behind the output is a real advantage, not just a cost.</p>
        </div>
      </details>

      <details class="acc">
        <summary><span class="sq">07</span>The unglamorous version usually wins</summary>
        <div class="acc-body">
          <p>The durable opportunities are rarely the exciting general-purpose ones. They're
          narrow, specific and slightly boring: one industry, one workflow, one painful hour
          of someone's week that you know intimately and your competitors don't.</p>
          <p><strong>Which means your existing career is an asset, not a handicap.</strong> The
          AI expertise is learnable in months. The twenty years of knowing exactly where a
          particular job hurts is not.</p>
        </div>
      </details>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="keepgoing">
  <div class="wrap">
    <p class="slabel">Staying current</p>
    <h2>How to keep learning without drowning in it</h2>
    <p>
      No reading list here, on purpose: links rot and a stale list looks authoritative.
      What doesn't rot is the routine.
    </p>
    <ul class="clean">
      <li><strong>Use it weekly on real work.</strong> Everything else is optional. Nothing substitutes for this.</li>
      <li><strong>Re-run your five prompts each quarter.</strong> That's your entire "keeping up with model news" obligation.</li>
      <li><strong>Read the model makers' own documentation</strong> when you want the truth about a product, rather than commentary about it.</li>
      <li><strong>Follow two or three people who show failures</strong>, not highlight reels. Anyone whose examples always work is showing you a demo.</li>
      <li><strong>Repeat your calibration test</strong> on your own area of expertise twice a year. Your working assumption about how often it's wrong should move as the tools move.</li>
      <li><strong>Teach someone.</strong> The fastest way to discover the parts you only think you understand.</li>
    </ul>

    <div class="note note-info">
      <span class="nlabel">Where this ends</span>
      <p>The goal was never to become an AI expert. It was to stop guessing in the dark —
      to know roughly what's possible, to get real help from it, and to be able to tell
      whether what you got back is any good. That's a normal, achievable competence, and
      it's most of the value on offer.</p>
    </div>
  </div>
</section>`;
