/* AI Hub — content for index.html
   The shell (head, nav, hero, pager, footer) is generated by src/layout.js
   from site.config.js. This file is ONLY the body content. */
'use strict';

const C = require("../components.js");

module.exports = `<!-- ============================================================ -->
<section id="uses">
  <div class="wrap">
    <p class="slabel">Before any theory</p>
    <h2>The kind of thing people use it for</h2>
    <p class="lead">
      Real shapes of use, in plain words. None of them need any technical skill.
    </p>
    <ul class="clean" id="use-list">
      <li>A restaurant owner pastes next week's staff availability — and gets a rota to argue with. <a href="map.html#audit">how</a></li>
      <li>A retired teacher pastes a pension letter — and asks what it means, in plain words. <a href="map.html#audit">how</a></li>
      <li>A nurse asks what to ask the doctor — before the appointment, not after. <a href="map.html#audit">how</a></li>
      <li>A manager turns an hour of meeting notes into decisions, owners and dates. <a href="map.html#audit">how</a></li>
      <li>Someone about to repost a statistic checks the source actually exists. <a href="trust.html#moves">how</a></li>
      <li>A parent rehearses a hard conversation — with the AI playing the other person. <a href="map.html#audit">how</a></li>
    </ul>
    <p class="small muted">These are shapes of use, not testimonials — the pages below show
    exactly how to do each one, and how to check what comes back.</p>

    <div class="note note-info" id="firsttime">
      <span class="nlabel">If you have never used one at all</span>
      <p>You cannot break anything, and reading this site commits you to nothing — no
      account, no download. Three things worth knowing before a first try: the big tools
      are free to start. Don't type anything private. And it sounds confident even when it
      is wrong — that is what the <a href="trust.html">Trust</a> page is for. When you do
      try, the first thing to type can simply be: <em>"Explain [anything you have always
      wondered about] in plain words."</em> A good first time is with someone beside you.</p>
    </div>
  </div>
</section>


<!-- ============================================================ -->
<section id="sixty">
  <div class="wrap">
    <p class="slabel">Before anything else</p>
    <h2>The short version</h2>
    <p class="lead">Six true things. If you read nothing else here, read these.</p>

    <figure class="fig">
      <svg viewBox="0 0 380 175" role="img" aria-label="Diagram: a search engine retrieves an existing page; an AI chatbot composes a new answer word by word">
        <text x="95" y="18" text-anchor="middle" font-size="14" font-weight="620" fill="var(--text)">Search finds</text>
        <text x="285" y="18" text-anchor="middle" font-size="14" font-weight="620" fill="var(--text)">AI composes</text>
        <circle cx="95" cy="45" r="10" fill="var(--blue-bg)" stroke="var(--blue)" stroke-width="1.5"/>
        <text x="95" y="49" text-anchor="middle" font-size="11" fill="var(--blue)">?</text>
        <circle cx="285" cy="45" r="10" fill="var(--blue-bg)" stroke="var(--blue)" stroke-width="1.5"/>
        <text x="285" y="49" text-anchor="middle" font-size="11" fill="var(--blue)">?</text>
        <line x1="95" y1="57" x2="95" y2="76" stroke="var(--text-ter)" stroke-width="1.5"/>
        <line x1="285" y1="57" x2="285" y2="76" stroke="var(--text-ter)" stroke-width="1.5"/>
        <rect x="30" y="82" width="130" height="16" rx="4" fill="var(--surface2)" stroke="var(--border-med)" stroke-width="1"/>
        <rect x="30" y="103" width="130" height="18" rx="4" fill="var(--green-bg)" stroke="var(--green)" stroke-width="1.2"/>
        <rect x="30" y="126" width="130" height="16" rx="4" fill="var(--surface2)" stroke="var(--border-med)" stroke-width="1"/>
        <text x="95" y="116" text-anchor="middle" font-size="10.5" fill="var(--green)">a page someone wrote</text>
        <rect x="216" y="96" width="30" height="20" rx="4" fill="var(--green-bg)" stroke="var(--green)" stroke-width="1.2"/>
        <rect x="251" y="96" width="30" height="20" rx="4" fill="var(--green-bg)" stroke="var(--green)" stroke-width="1.2"/>
        <rect x="286" y="96" width="30" height="20" rx="4" fill="var(--green-bg)" stroke="var(--green)" stroke-width="1.2"/>
        <rect x="321" y="96" width="30" height="20" rx="4" fill="none" stroke="var(--border-med)" stroke-width="1" stroke-dasharray="3 3"/>
        <text x="231" y="110" text-anchor="middle" font-size="10" fill="var(--green)">word</text>
        <text x="266" y="110" text-anchor="middle" font-size="10" fill="var(--green)">by</text>
        <text x="301" y="110" text-anchor="middle" font-size="10" fill="var(--green)">word</text>
        <text x="336" y="110" text-anchor="middle" font-size="12" fill="var(--text-ter)">…</text>
        <text x="95" y="162" text-anchor="middle" font-size="11" fill="var(--text-sec)">picked from what exists</text>
        <text x="285" y="162" text-anchor="middle" font-size="11" fill="var(--text-sec)">assembled on the spot</text>
      </svg>
      <figcaption>Search retrieves. A chatbot composes — one word at a time.</figcaption>
    </figure>

    <ol class="steps">
      <li>
        <h3>No human is typing the reply.</h3>
        <p class="muted">It is a program in a data centre. Answers vary because a little randomness is built in on purpose, not because you got a different person. That does not make it private: conversations can be stored, sometimes read by staff checking for misuse, and on a work account seen by your employer. What that means for you is on the <a href="trust.html#privacy">Trust</a> page.</p>
      </li>
      <li>
        <h3>It is not a search engine.</h3>
        <p class="muted">Search finds pages someone already wrote. A chatbot <em>composes</em> an answer word by word instead. Nobody checked it before it reached you — which is why it can be brilliant, and why it can be fluently wrong.</p>
      </li>
      <li>
        <h3>It predicts language. It does not "know" things.</h3>
        <p class="muted">It learned which words tend to follow which, from an enormous amount of writing. Being right is a side effect of that, never a guarantee.</p>
        <p class="muted">Afterwards, people rate its answers, and it is tuned toward the answers people like. That is what makes it helpful and polite — and also keen to agree with you.</p>
      </li>
      <li>
        <h3>It sounds equally confident whether it is right or wrong.</h3>
        <p class="muted">There is no wobble in its voice when it invents something — it sounds just as sure when it is wrong. Confidence carries no information. That one fact is why the <a href="trust.html">Trust</a> track exists.</p>
      </li>
      <li>
        <h3>It is not a companion, even when it feels like one.</h3>
        <p class="muted">The warmth is a property of the text, not of a mind that cares. It has no stake in your life. Useful, yes — just don't mistake the feeling for a relationship.</p>
      </li>
      <li>
        <h3>The skill is not "prompting". It is judgement.</h3>
        <p class="muted">The people getting real value are not the ones with magic words, but the ones who can tell a good answer from a plausible one.</p>
      </li>
    </ol>
  </div>
</section>

<!-- ============================================================ -->
<section id="tracks">
  <div class="wrap">
    <p class="slabel">The six tracks</p>
    <h2>Pick where you are. Nothing here has to be done in order.</h2>
    <p class="lead">
      Each track is one page. Each page is skimmable in five minutes and expandable
      when you want the detail.
    </p>

    ${C.trackGrid()}
  </div>
</section>

<!-- ============================================================ -->
<section id="problem">
  <div class="wrap">
    <p class="slabel">The problem, named</p>
    <h2>You are not behind. The ground is genuinely unclear.</h2>
    <p class="lead">
      Built from one page of notes on what makes AI confusing right now. If any of these
      six are yours, you are in the right place — and in very ordinary company.
    </p>

    <div class="grid grid-2">
      <div class="card">
        <span class="num">01</span>
        <h3>Noise everywhere, training nowhere</h3>
        <p class="small muted">It is on the news, on billboards, in every company meeting — and in nobody's training budget.</p>
      </div>
      <div class="card">
        <span class="num">02</span>
        <h3>Too many teachers, no way to grade them</h3>
        <p class="small muted">The tutorials are endless. Some good, some vague, some far too deep — and nothing tells you which before you've spent the hour.</p>
      </div>
      <div class="card">
        <span class="num">03</span>
        <h3>Too many models, no idea which is right</h3>
        <p class="small muted">New names every month, each claiming to be the best, several free until a limit nobody explained. Choosing feels like a guess you're not qualified to make.</p>
      </div>
      <div class="card">
        <span class="num">04</span>
        <h3>The mental model is usually wrong</h3>
        <p class="small muted">Nobody was handed a working picture of what it is, so people guess: a better search engine, a person typing back, something like a friend. Every guess is sensible, and each produces a different bad habit.</p>
      </div>
      <div class="card">
        <span class="num">05</span>
        <h3>No way to check the answer</h3>
        <p class="small muted">The big one. Nobody teaches how to check what comes back — and an answer you can't check is not an answer you can use.</p>
      </div>
      <div class="card">
        <span class="num">06</span>
        <h3>Same starting line, no visible line</h3>
        <p class="small muted">Nobody has twenty years of experience with this — young or old, working or retired. The gap is months of practice, not a degree. The problem is finding the start.</p>
      </div>
    </div>

    <div class="note note-info" style="margin-top:20px">
      <span class="nlabel">Why this hub exists</span>
      <p>Every section below exists to close one of those six gaps. Nothing here needs any
      technical background, and everything here is meant to be tested against your own
      experience rather than believed — including the claims on this page.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="honest">
  <div class="wrap">
    <p class="slabel">Ground rules</p>
    <h2>What this is, and what it isn't</h2>

    <div class="grid grid-2">
      <div class="card">
        <h3>What it is</h3>
        <ul class="clean yes small" style="margin-top:8px">
          <li>Plain language. No jargon without a translation.</li>
          <li>Free, with no account and nothing to install.</li>
          <li>Honest about what nobody knows yet.</li>
          <li>Focused on judgement, not tricks.</li>
        </ul>
      </div>
      <div class="card">
        <h3>What it isn't</h3>
        <ul class="clean no small" style="margin-top:8px">
          <li>Not a certificate, not a course, not selling you anything.</li>
          <li>Not sponsored by, or ranking, any AI company. Nothing here is paid for or affiliated.</li>
          <li>Not a live leaderboard — model names age in weeks.</li>
          <li>Not a substitute for a doctor, lawyer, or accountant.</li>
        </ul>
      </div>
    </div>

    <div class="note note-warn">
      <span class="nlabel">Read this page the way it teaches you to read AI</span>
      <p>This hub was written on <strong>5 August 2026</strong>. The ideas here are durable;
      specific product names, prices and limits are not, and are deliberately kept out of it.
      Where a fact could go stale, the page says so instead of pretending. If something here
      contradicts what you can verify yourself today — trust what you verified.</p>
    </div>
  </div>
</section>`;
