/* AI Hub — content for index.html
   The shell (head, nav, hero, pager, footer) is generated by src/layout.js
   from site.config.js. This file is ONLY the body content. */
'use strict';

const C = require("../components.js");

module.exports = `<!-- ============================================================ -->
<section id="problem">
  <div class="wrap">
    <p class="slabel">The problem, named</p>
    <h2>You are not behind. The ground is genuinely unclear.</h2>
    <p class="lead">
      This hub was built from one page of notes about what actually makes AI confusing
      right now. Six problems came out of it. If any of these are yours, you are in the
      right place — and you are in very ordinary company.
    </p>

    <div class="grid grid-2">
      <div class="card">
        <span class="num">01</span>
        <h4>Noise everywhere, training nowhere</h4>
        <p class="small muted">AI is on the news, in podcasts, on cars, trains and billboards, and in every company all-hands. Employers say "embrace AI to improve productivity" — and then run no formal training at all.</p>
      </div>
      <div class="card">
        <span class="num">02</span>
        <h4>Too many teachers, no way to grade them</h4>
        <p class="small muted">YouTube and Instagram are full of AI tutorials. Some are good. Some are vague. Some are too simple to use, some too deep to follow. Nothing tells you which is which before you've wasted the hour.</p>
      </div>
      <div class="card">
        <span class="num">03</span>
        <h4>Too many models, no idea which is right</h4>
        <p class="small muted">New names every month, each claiming to be the best. Several look free — until you hit a limit nobody explained. Choosing feels like a bet you're not qualified to place.</p>
      </div>
      <div class="card">
        <span class="num">04</span>
        <h4>The mental model is usually wrong</h4>
        <p class="small muted">Some people have no idea what AI is. Some think it's a chatbot replacing Google search. Some think a person is typing back. Some come to treat it as a real companion. Each wrong picture produces a different wrong habit.</p>
      </div>
      <div class="card">
        <span class="num">05</span>
        <h4>No way to check the answer</h4>
        <p class="small muted">This is the big one. Nobody teaches how to validate what an AI produces. Blind trust isn't leverage — it's a risk you can't see. An answer you can't check is not an answer you can use.</p>
      </div>
      <div class="card">
        <span class="num">06</span>
        <h4>Same starting line, no visible line</h4>
        <p class="small muted">AI did reset everyone to roughly the same page — young or old, technical or not. But a fair start is useless if nobody can find the start. Most people are shooting in the dark.</p>
      </div>
    </div>

    <div class="note note-info" style="margin-top:20px">
      <span class="nlabel">Why this hub exists</span>
      <p>Every section below exists to close one of those six gaps. Nothing here needs any
      technical background, and nothing here asks you to take a claim on faith — including
      the claims on this page.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="sixty">
  <div class="wrap">
    <p class="slabel">Before anything else</p>
    <h2>The 60-second version</h2>
    <p class="lead">Six true things. If you only ever read one screen of this hub, read this one.</p>

    <ol class="steps">
      <li>
        <h4>No human is behind it.</h4>
        <p class="muted">Nobody reads your message. It is a program running on a computer in a data centre. It gives different answers to the same question because a little randomness is built in on purpose — not because you got a different person.</p>
      </li>
      <li>
        <h4>It is not a search engine.</h4>
        <p class="muted">Search finds pages that someone already wrote. An AI chatbot <em>composes</em> a new answer, word by word, that has never existed before. That is why it can be brilliant — and why it can be confidently, fluently wrong.</p>
      </li>
      <li>
        <h4>It predicts language. It does not "know" things.</h4>
        <p class="muted">It was trained on an enormous amount of writing and learned which words tend to follow which. Being right is usually a side effect of that. It is never a guarantee.</p>
      </li>
      <li>
        <h4>It sounds equally confident whether it is right or wrong.</h4>
        <p class="muted">There is no wobble in its voice when it invents something. Confidence carries no information. This single fact is why the <a href="trust.html">Trust</a> track exists.</p>
      </li>
      <li>
        <h4>It is not a companion, even when it feels like one.</h4>
        <p class="muted">The warmth is a property of the text, not of a mind that cares about you. It has no stake in your life, and no memory of you unless the product was built to keep one. It can still be genuinely useful — just don't mistake the feeling for a relationship.</p>
      </li>
      <li>
        <h4>The skill is not "prompting". It is judgement.</h4>
        <p class="muted">The people getting real value are not the ones with magic words. They are the ones who know what to ask for, and can tell a good answer from a plausible one.</p>
      </li>
    </ol>
  </div>
</section>

<!-- ============================================================ -->
<section id="tracks">
  <div class="wrap">
    <p class="slabel">The five tracks</p>
    <h2>Pick where you are. Nothing here has to be done in order.</h2>
    <p class="lead">
      Each track is one page. Each page is skimmable in five minutes and expandable
      when you want the detail.
    </p>

    ${C.trackGrid()}
  </div>
</section>

<!-- ============================================================ -->
<section id="honest">
  <div class="wrap">
    <p class="slabel">Ground rules</p>
    <h2>What this is, and what it isn't</h2>

    <div class="grid grid-2">
      <div class="card">
        <h4>What it is</h4>
        <ul class="clean yes small" style="margin-top:8px">
          <li>Plain language. No jargon without a translation.</li>
          <li>Free, with no account and nothing to install.</li>
          <li>Honest about what nobody knows yet.</li>
          <li>Focused on judgement, not tricks.</li>
        </ul>
      </div>
      <div class="card">
        <h4>What it isn't</h4>
        <ul class="clean no small" style="margin-top:8px">
          <li>Not a certificate, a course, or a funnel.</li>
          <li>Not sponsored by, or ranking, any AI company.</li>
          <li>Not a live leaderboard — model names age in weeks.</li>
          <li>Not a substitute for a doctor, lawyer, or accountant.</li>
        </ul>
      </div>
    </div>

    <div class="note note-warn">
      <span class="nlabel">Read this page the way it teaches you to read AI</span>
      <p>This hub was written on <strong>5 August 2026</strong>. The ideas here are durable;
      specific product names, prices and limits are not, and are deliberately kept out of it.
      Where a fact could go stale, the page says so instead of pretending. If something here
      contradicts what you can verify yourself today — trust what you verified.</p>
    </div>
  </div>
</section>`;
