/* AI Hub — content for index.html
   The shell (head, nav, hero, pager, footer) is generated by src/layout.js
   from site.config.js. This file is ONLY the body content. */
'use strict';

const C = require("../components.js");

module.exports = `<!-- ============================================================ -->
<section id="problem">
  <div class="wrap">
    <p class="slabel">The problem, named</p>
    <h2>You are not behind. The ground is genuinely unclear.</h2>
    <p class="lead">
      This hub was built from one page of notes about what actually makes AI confusing
      right now. Six problems came out of it. If any of these are yours, you are in the
      right place — and you are in very ordinary company.
    </p>

    <div class="grid grid-2">
      <div class="card">
        <span class="num">01</span>
        <h3>Noise everywhere, training nowhere</h3>
        <p class="small muted">AI is on the news, in podcasts, on cars, trains and billboards, and in every company all-hands. Employers say "embrace AI to improve productivity" — and then run no formal training at all.</p>
      </div>
      <div class="card">
        <span class="num">02</span>
        <h3>Too many teachers, no way to grade them</h3>
        <p class="small muted">YouTube and Instagram are full of AI tutorials. Some are good. Some are vague. Some are too simple to use, some too deep to follow. Nothing tells you which is which before you've wasted the hour.</p>
      </div>
      <div class="card">
        <span class="num">03</span>
        <h3>Too many models, no idea which is right</h3>
        <p class="small muted">New names every month, each claiming to be the best. Several look free — until you hit a limit nobody explained. Choosing feels like a bet you're not qualified to place.</p>
      </div>
      <div class="card">
        <span class="num">04</span>
        <h3>The mental model is usually wrong</h3>
        <p class="small muted">Almost nobody was handed a working picture of what this thing is. So people reasonably guess: that it's a better search engine, that someone is answering, or — because it's warm and remembers what you just said — that it's something like a friend. Every one of those guesses is sensible. Each one quietly produces a different bad habit.</p>
      </div>
      <div class="card">
        <span class="num">05</span>
        <h3>No way to check the answer</h3>
        <p class="small muted">This is the big one. Nobody teaches how to validate what an AI produces. Blind trust isn't leverage — it's a risk you can't see. An answer you can't check is not an answer you can use.</p>
      </div>
      <div class="card">
        <span class="num">06</span>
        <h3>Same starting line, no visible line</h3>
        <p class="small muted">Nobody has twenty years of experience with this, which is a fairer start than most technologies offer — young or old, technical or not. It is not a level field: money, hardware and language still tilt it. But the gap is months of practice, not a degree. And a fair start is useless if nobody can find the start. Most people are shooting in the dark.</p>
      </div>
    </div>

    <div class="note note-info" style="margin-top:20px">
      <span class="nlabel">Why this hub exists</span>
      <p>Every section below exists to close one of those six gaps. Nothing here needs any
      technical background, and everything here is meant to be tested against your own
      experience rather than believed — including the claims on this page.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="sixty">
  <div class="wrap">
    <p class="slabel">Before anything else</p>
    <h2>The 60-second version</h2>
    <p class="lead">Six true things. If you only ever read one screen of this hub, read this one.</p>

    <ol class="steps">
      <li>
        <h3>No human is typing the reply.</h3>
        <p class="muted">It is a program running in a data centre. It gives different answers to the same question because a little randomness is built in on purpose — not because you got a different person. But "no one is typing" is not "no one can ever see it": conversations can be stored, sampled by staff reviewing safety, or read by your employer if the account is company-issued. What that means for you is on the <a href="trust.html#privacy">Trust</a> page.</p>
      </li>
      <li>
        <h3>It is not a search engine.</h3>
        <p class="muted">Search finds pages that someone already wrote. An AI chatbot <em>composes</em> an answer word by word instead of retrieving one. Usually the result is new; sometimes it reproduces wording it was trained on. Either way nobody checked it before it reached you — which is why it can be brilliant, and why it can be confidently, fluently wrong.</p>
      </li>
      <li>
        <h3>It predicts language. It does not "know" things.</h3>
        <p class="muted">It was trained on an enormous amount of writing and learned which words tend to follow which. Being right is usually a side effect of that. It is never a guarantee.</p>
        <p class="muted">It is then trained a second time on human ratings of its answers. That is what makes it helpful and polite — and also what makes it inclined to agree with you.</p>
      </li>
      <li>
        <h3>It sounds equally confident whether it is right or wrong.</h3>
        <p class="muted">There is no wobble in its voice when it invents something. Confidence carries no information. This single fact is why the <a href="trust.html">Trust</a> track exists.</p>
      </li>
      <li>
        <h3>It is not a companion, even when it feels like one.</h3>
        <p class="muted">The warmth is a property of the text, not of a mind that cares about you. It has no stake in your life, and no memory of you unless the product was built to keep one. It can still be genuinely useful — just don't mistake the feeling for a relationship.</p>
      </li>
      <li>
        <h3>The skill is not "prompting". It is judgement.</h3>
        <p class="muted">The people getting real value are not the ones with magic words. They are the ones who know what to ask for, and can tell a good answer from a plausible one.</p>
      </li>
    </ol>
  </div>
</section>

<!-- ============================================================ -->
<section id="tracks">
  <div class="wrap">
    <p class="slabel">The six tracks</p>
    <h2>Pick where you are. Nothing here has to be done in order.</h2>
    <p class="lead">
      Each track is one page. Each page is skimmable in five minutes and expandable
      when you want the detail.
    </p>

    ${C.trackGrid()}
  </div>
</section>

<!-- ============================================================ -->
<section id="honest">
  <div class="wrap">
    <p class="slabel">Ground rules</p>
    <h2>What this is, and what it isn't</h2>

    <div class="grid grid-2">
      <div class="card">
        <h3>What it is</h3>
        <ul class="clean yes small" style="margin-top:8px">
          <li>Plain language. No jargon without a translation.</li>
          <li>Free, with no account and nothing to install.</li>
          <li>Honest about what nobody knows yet.</li>
          <li>Focused on judgement, not tricks.</li>
        </ul>
      </div>
      <div class="card">
        <h3>What it isn't</h3>
        <ul class="clean no small" style="margin-top:8px">
          <li>Not a certificate, a course, or a funnel.</li>
          <li>Not sponsored by, or ranking, any AI company. Nothing here is paid for or affiliated.</li>
          <li>Not a live leaderboard — model names age in weeks.</li>
          <li>Not a substitute for a doctor, lawyer, or accountant.</li>
        </ul>
      </div>
    </div>

    <div class="note note-warn">
      <span class="nlabel">Read this page the way it teaches you to read AI</span>
      <p>This hub was written on <strong>5 August 2026</strong>. The ideas here are durable;
      specific product names, prices and limits are not, and are deliberately kept out of it.
      Where a fact could go stale, the page says so instead of pretending. If something here
      contradicts what you can verify yourself today — trust what you verified.</p>
    </div>
  </div>
</section>`;
