/* AI Hub — content for leverage.html
   The shell (head, nav, hero, pager, footer) is generated by src/layout.js
   from site.config.js. This file is ONLY the body content. */
'use strict';

module.exports = `<!-- ============================================================ -->
<section id="model">
  <div class="wrap">
    <p class="slabel">The mental model</p>
    <h2>Why that picture produces better results than any prompt trick</h2>
    <p class="lead">
      Every column below is a habit you already have with a new colleague. Applied here,
      they are most of what people call "prompt engineering".
    </p>

    <div class="tscroll">
      <table>
        <thead>
          <tr><th style="width:30%">Because it's…</th><th>You would naturally…</th></tr>
        </thead>
        <tbody>
          <tr><td><strong>New here</strong></td><td>Explain the situation before the task. Say who it's for and why it matters. Never assume they know your context.</td></tr>
          <tr><td><strong>Well-read but green</strong></td><td>Expect solid general knowledge and zero knowledge of your specifics. Hand over the actual documents.</td></tr>
          <tr><td><strong>Fast and tireless</strong></td><td>Ask for three versions instead of one. Iterate rather than agonising over the perfect first request.</td></tr>
          <tr><td><strong>Over-confident</strong></td><td>Check their work before it goes anywhere with your name on it. See <a href="trust.html">Trust</a>.</td></tr>
          <tr><td><strong>Not accountable</strong></td><td>Keep the decision yourself. Delegate the drafting, never the judgement.</td></tr>
        </tbody>
      </table>
    </div>

    <div class="note note-info">
      <span class="nlabel">The test</span>
      <p>Before sending a request, ask: <em>could a capable stranger do this task from what
      I've written?</em> If the answer is no, the AI can't either — and it will guess rather
      than tell you it's stuck. Nearly every disappointing answer traces back to a failed
      version of this test.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="anatomy">
  <div class="wrap">
    <p class="slabel">The craft</p>
    <h2>The five parts of a request that works</h2>
    <p class="lead">
      You don't need all five every time. But when an answer disappoints, one of these is
      almost always the missing piece.
    </p>

    <ol class="steps">
      <li><h3>Context — the situation</h3>
        <p class="muted">Who you are, who this is for, what's already happened, what
        constraints exist. This is the part beginners skip and experts over-deliver on.</p></li>
      <li><h3>Task — the actual verb</h3>
        <p class="muted">Not "help me with my email" but "rewrite this so it declines
        without closing the door." Vague verbs produce vague output.</p></li>
      <li><h3>Constraints — the boundaries</h3>
        <p class="muted">Length, tone, what to avoid, what must be included, what you've
        already tried and don't want repeated.</p></li>
      <li><h3>Format — the shape you want back</h3>
        <p class="muted">A table with these columns. Five bullets. An email under 150 words.
        Plain English, no jargon. Shape is free to ask for and enormously improves usability
        — and makes checking easier.</p></li>
      <li><h3>Example — one sample of "good"</h3>
        <p class="muted">The most powerful and least used ingredient. One example of what
        right looks like beats three paragraphs describing it.</p></li>
    </ol>

    <h3>The same request, before and after</h3>
    <div class="grid grid-2">
      <div class="card">
        <span class="tag tag-red">Before</span>
        <div class="prompt" style="margin-top:10px">Write an email to my team about the new process.</div>
        <p class="small muted" style="margin-top:10px">Result: something generic, corporate,
        and unusable — because every choice was left to a stranger who knows nothing.</p>
      </div>
      <div class="card">
        <span class="tag tag-green">After</span>
        <div class="prompt-wrap" style="margin-top:10px">
          <button class="copy-btn" type="button">Copy</button>
          <div class="prompt">I manage a team of 9 in customer support. From Monday we're moving from email to a shared ticket queue. The team is tired of tool changes — the last two were dropped after a month, so trust is low.

Write an email to them announcing it.

Constraints: under 200 words. Acknowledge the last two failures directly instead of pretending they didn't happen. No corporate cheer. Say plainly what's in it for them, and give one concrete thing they can do on Monday.

End with an open offer to hear objections.</div>
        </div>
      </div>
    </div>
    <p class="small muted">Nothing clever happened there. The second version simply told a
    new colleague what they'd need to know. That's the whole skill.</p>
  </div>
</section>

<!-- ============================================================ -->
<section id="iterate">
  <div class="wrap">
    <p class="slabel">The habit that matters most</p>
    <h2>Round one is not the answer. It's the opening move.</h2>
    <p>
      The single biggest difference between people who find AI useful and people who find
      it disappointing isn't prompt quality. It's that one group stops after the first
      reply and the other doesn't.
    </p>
    <p>
      Your first message is a guess about what you want, answered by a guess about what you
      meant. The value is in rounds two to five, where you say what was wrong with round one.
      That is not a failure of the tool — it's how the tool is meant to be used.
    </p>

    <div class="grid grid-3">
      <div class="card"><h3>Round 1</h3><p class="small muted">You see the shape of the answer, and discover what you actually wanted — which you often didn't know until you saw the wrong version.</p></div>
      <div class="card"><h3>Round 2–3</h3><p class="small muted">"Too formal." "You missed the cost angle." "Cut it in half." "Keep paragraph 2, redo the rest." Direct, blunt, specific.</p></div>
      <div class="card"><h3>Round 4–5</h3><p class="small muted">Now the material is genuinely yours. This is where the output stops being generic and starts being usable.</p></div>
    </div>

    <div class="note note-do">
      <span class="nlabel">Say what's wrong, not "try again"</span>
      <p>"Do it better" gets you a random reshuffle. "The second paragraph is too vague —
      give me the actual numbers, and drop the last line entirely" gets you the next draft.
      Be as direct as you'd never dare be with a person. It genuinely does not mind.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="upgrade">
  <div class="wrap">
    <p class="slabel">The biggest single upgrade</p>
    <h2>Stop describing the material. Give it the material.</h2>
    <p>
      Most people type a description of the thing they're working on. Then they're
      disappointed that the answer is generic — but a description is all the AI had.
    </p>
    <div class="note note-warn">
      <span class="nlabel">Before you paste anything, one question</span>
      <p>Is this yours to share? Work documents, customer data, colleagues' details and
      anything under a confidentiality agreement are covered by the
      <a href="trust.html#privacy">never-paste list</a> — and a sales spreadsheet or a client
      report is almost always your employer's, not yours. Use the tool your employer approved,
      or don't use one.</p>
    </div>
    <div class="grid grid-2">
      <div class="note note-dont" style="margin:0">
        <span class="nlabel">Describing</span>
        <p>"I have a long report about my local council's budget and I want to know what's going on."</p>
      </div>
      <div class="note note-do" style="margin:0">
        <span class="nlabel">Giving</span>
        <p>Paste or upload the actual document. Then: "What stands out? What would you check
        before believing it? What's missing that I'd want for a decision?"</p>
      </div>
    </div>
    <p style="margin-top:16px">
      Same for the transcript, the error message, the rejection letter, the job description,
      the manual nobody can find. The more real the document, the bigger the gain — and the
      more the privacy question above applies.
    </p>
  </div>
</section>

<!-- ============================================================ -->
<section id="patterns">
  <div class="wrap">
    <p class="slabel">Steal these</p>
    <h2>Ten patterns that work in almost any situation</h2>
    <p class="lead">Each is a role you can put it in. Copy, paste, replace the bracketed part.</p>

    <div class="acc-tools">
      <button type="button" data-acc="open">Expand all</button>
      <button type="button" data-acc="close">Collapse all</button>
    </div>

    <details class="acc" open>
      <summary><span class="sq">01</span>The tutor</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">Teach me [topic]. I know nothing about it. Don't lecture — go one small step at a time, and after each step ask me a question to check I followed. If I get it wrong, explain what I misunderstood before moving on.</div></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">02</span>The critic</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">Here is [my work]. Don't tell me what's good. Tell me the three weakest things about it, why each is weak, and what would fix it. Be blunt — I'd rather hear it from you than from my audience.</div></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">03</span>The translator</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">Rewrite this for [audience], who [what they care about and what they don't]. Same meaning, nothing added or softened. Then tell me which parts I'm likely to be challenged on.</div></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">04</span>The explainer</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">Explain [thing] to me three times: once as if I'm ten, once as if I'm a smart adult with no background, and once as if I work in the field. Then tell me which one I probably need.</div></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">05</span>The devil's advocate</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">I'm about to [decision]. Argue against it as forcefully as you can. Then tell me which of your arguments is strongest, and what evidence would change my mind.</div></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">06</span>The rehearsal partner</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">You are [the other person: interviewer / my landlord / a sceptical client]. I'm going to [what I want]. Play them realistically, including being difficult. One exchange at a time — wait for my reply before continuing.</div></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">07</span>The extractor</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">Here is [messy text]. Turn it into a table with these exact columns: [columns]. If a value isn't stated, write "not stated" — do not guess or fill it in. List anything that didn't fit the table underneath.</div></div>
        <p class="small muted" style="margin-top:10px">The "do not guess" instruction is the important half. Without it, gaps get quietly filled with plausible inventions.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">08</span>The pre-mortem</summary>
      <div class="acc-body">
        <p class="small muted">A technique from decision researcher Gary Klein
        (<em>Harvard Business Review</em>, 2007): imagine the failure has already happened,
        then explain how. The idea is his; the wording below is ours.</p>
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">It's six months from now and [my plan] has failed badly. Write the story of how it failed. Then rank the causes by how likely they are, and tell me which one I could cheaply protect against this week.</div></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">09</span>The question-finder</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">I'm about to meet [a doctor / lawyer / builder / recruiter] about [situation]. What should I ask them that someone in my position usually doesn't think to ask? What would I regret not asking?</div></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">10</span>The unsticker</summary>
      <div class="acc-body">
        <div class="prompt-wrap"><button class="copy-btn" type="button">Copy</button>
        <div class="prompt">I'm stuck on [problem]. I've already tried [what you tried]. Ask me questions until you understand the situation properly — don't propose anything until you do.</div></div>
        <p class="small muted" style="margin-top:10px">Making it interview <em>you</em> is the most underused move there is. It surfaces the thing you left out because it seemed obvious.</p>
      </div>
    </details>
  </div>
</section>

<!-- ============================================================ -->
<section id="mistakes">
  <div class="wrap">
    <p class="slabel">Save yourself the time</p>
    <h2>Seven beginner mistakes, in order of how much they cost</h2>

    <div class="tscroll">
      <table>
        <thead><tr><th style="width:34%">Mistake</th><th>Fix</th></tr></thead>
        <tbody>
          <tr><td><strong>Stopping after one reply</strong></td><td>Treat round one as a draft. The value is in the corrections.</td></tr>
          <tr><td><strong>Describing instead of pasting</strong></td><td>Give it the real document. Generic input, generic output.</td></tr>
          <tr><td><strong>No context about you</strong></td><td>Say who you are, who it's for, and what you're going to do with it.</td></tr>
          <tr><td><strong>Asking for facts, not thinking</strong></td><td>It's much stronger at structuring, criticising and explaining than at recalling. Use search for lookups.</td></tr>
          <tr><td><strong>Shipping the first draft</strong></td><td>Its default voice is recognisable and bland. Rewrite in your own words — that's also how you catch its errors.</td></tr>
          <tr><td><strong>Being polite instead of clear</strong></td><td>"Could you perhaps make it a bit shorter?" → "Cut to 120 words. Drop the third paragraph."</td></tr>
          <tr><td><strong>One giant request</strong></td><td>Break it into steps and check each. A wrong step four is invisible inside a wall of output.</td></tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="tiers">
  <div class="wrap">
    <p class="slabel">When to move up a gear</p>
    <h2>Three levels of tool. Most people never leave the first.</h2>

    <div class="grid grid-3">
      <div class="card">
        <span class="num">Level 1</span>
        <h3>Chat</h3>
        <p class="small muted">Type a question, get an answer. Fine for most things, and where everyone starts.</p>
        <p class="small muted"><strong>Move on when:</strong> you're pasting the same background into every new conversation.</p>
      </div>
      <div class="card">
        <span class="num">Level 2</span>
        <h3>Chat with your files</h3>
        <p class="small muted">Upload documents, keep a persistent set of instructions, work over your own material rather than general knowledge.</p>
        <p class="small muted"><strong>Move on when:</strong> you want it to <em>do</em> things, not just produce text about them.</p>
      </div>
      <div class="card">
        <span class="num">Level 3</span>
        <h3>Agents and coding tools</h3>
        <p class="small muted">It takes multiple steps on its own — searching, running code, editing files, checking its own work.</p>
        <p class="small muted"><strong>The catch:</strong> more autonomy, more to verify, and far more it can break in one go when it's wrong.</p>
      </div>
    </div>

    <div class="note note-warn">
      <span class="nlabel">Rule for level 3</span>
      <p>Never let it act unsupervised on something you couldn't undo. Work on copies, keep
      backups, and read what it did before you accept it. Autonomy is a multiplier — it
      multiplies mistakes just as efficiently as it multiplies work.</p>
    </div>
  </div>
</section>`;
