/* AI Hub — content for map.html
   The shell (head, nav, hero, pager, footer) is generated by src/layout.js
   from site.config.js. This file is ONLY the body content. */
'use strict';

module.exports = `<!-- ============================================================ -->
<section id="whyblind">
  <div class="wrap">
    <p class="slabel">The real bottleneck</p>
    <h2>Most people use a fraction of it, and never find out</h2>
    <p>
      Ask someone who has had an AI chatbot for a year what they use it for, and you'll
      often get two answers: writing emails, and looking things up. Both work. Both are
      a rounding error on what the tool does.
    </p>
    <p>
      This isn't a failure of intelligence or effort. It's structural. A search engine
      teaches you its limits quickly — you type something, you get nothing useful, you
      learn. An AI chatbot always answers. It never says "that's not what I'm for."
      So you never bump into the edges, and you never discover the rooms you didn't
      walk into.
    </p>
    <div class="note note-info">
      <span class="nlabel">The shape of the problem</span>
      <p>Your blind spot isn't a wrong belief you could argue with. It's an absent
      question. The fix isn't a better answer — it's exposure to the range, and a habit
      of going looking.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="good">
  <div class="wrap">
    <p class="slabel">The menu</p>
    <h2>Ten things it is genuinely good at</h2>
    <p class="lead">
      Not a feature list — a list of <em>shapes of work</em>. Most useful requests are one
      of these ten wearing different clothes. Open any that you haven't tried.
    </p>

    <div class="acc-tools">
      <button type="button" data-acc="open">Expand all</button>
      <button type="button" data-acc="close">Collapse all</button>
    </div>

    <details class="acc">
      <summary><span class="sq">01</span>Turning one form into another</summary>
      <div class="acc-body">
        <p>Messy notes into a clean summary. A transcript into minutes with action items.
        A table into a paragraph. A paragraph into a table. An email chain into a timeline.
        A spec into a checklist.</p>
        <p class="small muted">This is the single most reliable category, because the answer
        is already contained in what you gave it. Nothing has to be invented, so there's
        much less to get wrong.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">02</span>Explaining anything at any level</summary>
      <div class="acc-body">
        <p>The same idea explained to a ten-year-old, to a smart adult with no background,
        and to a specialist. You can say "I got lost at the third sentence — start again
        from there" as many times as you need, and it never gets impatient.</p>
        <p class="small muted">Underrated: paste in the thing you don't understand — a legal
        clause, an error message, a doctor's letter, a tax form — and ask what it means in
        ordinary words, and what it means <em>for you</em>.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">03</span>Beating the blank page</summary>
      <div class="acc-body">
        <p>A first draft of anything: an awkward email, a complaint letter, a job
        description, a speech, a policy, a plan. Not because the draft is good — usually
        it's mediocre — but because reacting to a mediocre draft is ten times easier
        than starting from nothing.</p>
        <div class="note note-warn"><span class="nlabel">Careful</span>
        <p>Mediocre is the risk. If you ship the first draft, you ship generic. The value
        is in what <em>you</em> change.</p></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">04</span>Criticising work — including yours</summary>
      <div class="acc-body">
        <p>"What's the weakest part of this argument?" "What would a hostile reviewer
        attack first?" "What am I assuming here without saying so?" "What's missing that
        an expert would expect to see?"</p>
        <p class="small muted">This is where a lot of the real value hides, and almost
        nobody uses it. It's more useful than asking it to write for you, because a
        critique you disagree with is still information.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">05</span>Pulling structure out of mess</summary>
      <div class="acc-body">
        <p>Fifty customer emails into five themes with counts. A pile of receipts into
        categories. A long thread into "who is asking for what, and by when."
        An unstructured page of notes into a table with consistent columns.</p>
        <p class="small muted">Ask for the output as a table or a list with fixed fields —
        structure in the request produces structure in the answer, and structured answers
        are far easier to check.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">06</span>Being a tutor with infinite patience</summary>
      <div class="acc-body">
        <p>Not "explain X" but "teach me X. Ask me a question, wait for my answer,
        tell me what I got wrong, then go one step further." A tutor that never sighs,
        never runs out of time, and doesn't mind that you asked the same thing twice.</p>
        <p class="small muted">For anyone who left school long ago, or who never had access
        to good teaching, this is arguably the most life-changing thing on this page.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">07</span>Rehearsal for something real</summary>
      <div class="acc-body">
        <p>"You are the hiring manager. Interview me for this job, one question at a time,
        and be tough." Or the difficult conversation with a colleague. Or the negotiation.
        Or explaining your diagnosis back to your doctor so you know you understood it.</p>
        <p class="small muted">Nobody sees you get it wrong. That's the whole point.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">08</span>Translation — between languages, and between worlds</summary>
      <div class="acc-body">
        <p>Between human languages, yes. But also: engineer to executive, legal to plain
        English, doctor to patient, angry to professional. "Rewrite this so it says the
        same thing but doesn't sound furious" is a genuinely valuable service.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">09</span>Writing and fixing code — even if you can't</summary>
      <div class="acc-body">
        <p>A spreadsheet formula. A script that renames 400 files. A small web page.
        A fix for an error message you don't understand. You do not need to be a
        programmer to get real use out of this — you need to be able to test the result.</p>
        <div class="note note-warn"><span class="nlabel">The rule</span>
        <p>Never run code you can't test the effect of, and never run something that
        deletes or overwrites without a copy of the original. Code that runs is not the
        same as code that is correct.</p></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">10</span>Thinking out loud with something that answers</summary>
      <div class="acc-body">
        <p>Half-formed idea, no audience, 11pm. "Here's what I'm thinking, poke holes."
        "Give me three ways to look at this that I haven't considered." "What would
        someone who disagrees with me say?"</p>
        <p class="small muted">Not because it's wise. Because articulating a problem to
        something that responds is how a lot of people find out what they actually think.</p>
      </div>
    </details>
  </div>
</section>

<!-- ============================================================ -->
<section id="bad">
  <div class="wrap">
    <p class="slabel">The other half of the map</p>
    <h2>Eight things it is bad at — structurally, not temporarily</h2>
    <p class="lead">
      These aren't bugs waiting for the next version. Most follow directly from how the
      thing works: it produces likely-looking language, one piece at a time.
    </p>

    <div class="tscroll">
      <table>
        <thead>
          <tr><th>It is bad at</th><th>Because</th><th>What to do instead</th></tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>Knowing today's facts</strong></td>
            <td>Its knowledge stops at a training cutoff date. Anything after that, it will either refuse or invent.</td>
            <td>Use a tool that actually searches the web, and open the sources it gives you.</td>
          </tr>
          <tr>
            <td><strong>Knowing what it doesn't know</strong></td>
            <td>Nothing in it separates "recalled" from "made up". Both come out sounding the same.</td>
            <td>Assume every specific claim is a claim, not a fact, until you've checked it.</td>
          </tr>
          <tr>
            <td><strong>Arithmetic and counting</strong></td>
            <td>It predicts the <em>look</em> of a number. Long sums, percentages of percentages, and counting items in a list all drift.</td>
            <td>Do the maths yourself, or use a tool that genuinely calculates and shows its working.</td>
          </tr>
          <tr>
            <td><strong>Anything about you</strong></td>
            <td>Unless the product was built to remember, each conversation starts from nothing. It doesn't know your company, your files, or last week.</td>
            <td>Give it the context every time — paste the actual document rather than describing it.</td>
          </tr>
          <tr>
            <td><strong>Saying "no"</strong></td>
            <td>It is built to be helpful. A confident wrong answer is a more likely piece of text than a refusal.</td>
            <td>Explicitly permit it: "If you don't know, say so." It helps. It is not a guarantee.</td>
          </tr>
          <tr>
            <td><strong>Holding a position under pressure</strong></td>
            <td>Push back and it will often fold and agree with you, whether or not you were right.</td>
            <td>Never use "are you sure?" as your fact-check. Check the fact somewhere else.</td>
          </tr>
          <tr>
            <td><strong>Genuine novelty</strong></td>
            <td>It reflects patterns in what already exists. Ask for something original and you often get a competent average.</td>
            <td>Use it to widen your options, then bring your own taste to choose and sharpen.</td>
          </tr>
          <tr>
            <td><strong>Consequences</strong></td>
            <td>It has no stake in the outcome. It will not be there when the plan fails, the money is gone, or the letter is sent.</td>
            <td>Keep the decision. Delegate the drafting, never the accountability.</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="jagged">
  <div class="wrap">
    <p class="slabel">The part that surprises everyone</p>
    <h2>It is not uniformly clever. The edge is jagged.</h2>
    <p>
      People expect ability to be a single dial: a bit smart, quite smart, very smart.
      That intuition is wrong here, and it's the reason so many first impressions are
      either "this is magic" or "this is useless" — both formed from one lucky or unlucky
      question.
    </p>
    <p>
      In practice the boundary between what it does brilliantly and what it fails at is
      ragged and unintuitive. It can produce a genuinely expert paragraph about immunology
      and then miscount the letters in a word. Neither result tells you much about the next
      task. Researchers studying consultants using AI at work named this shape the
      <strong>"jagged technological frontier"</strong> — a useful term, and not ours;
      it comes from a 2023 Harvard Business School and Boston Consulting Group working paper
      by Dell'Acqua and colleagues.
    </p>

    <div class="grid grid-2">
      <div class="note note-dont" style="margin:0">
        <span class="nlabel">What people conclude</span>
        <p>"It got that wrong, so it's useless." Or: "It nailed that, so I can trust it
        on the next thing." Both are the same mistake — generalising from one point.</p>
      </div>
      <div class="note note-do" style="margin:0">
        <span class="nlabel">What to conclude instead</span>
        <p>Ability is task-shaped, not level-shaped. The only way to know where the edge
        sits for <em>your</em> work is to test it on your work — and to keep testing, because
        the edge moves with every model release.</p>
      </div>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="habits">
  <div class="wrap">
    <p class="slabel">The antidote</p>
    <h2>Five habits that find your blind spots for you</h2>
    <p class="lead">
      You can't list what you don't know. But you can run a process that keeps
      surfacing it. These five cost almost nothing and compound quickly.
    </p>

    <ol class="steps">
      <li>
        <h4>Keep a friction log for one week</h4>
        <p class="muted">Every time something at work or at home is tedious, repetitive, or
        makes you sigh — write one line in a note. Don't judge, just log. At the end of the
        week you're holding a list of the AI-shaped holes in your life. This finds far more
        than any "100 prompts" article, because it's about your actual days.</p>
      </li>
      <li>
        <h4>Ask it what you should have asked</h4>
        <p class="muted">The cheapest trick on this whole site. At the end of any exchange:</p>
        <div class="prompt-wrap">
          <button class="copy-btn" type="button">Copy</button>
          <div class="prompt">What should I have asked you that I didn't? What do people in my situation usually miss here?</div>
        </div>
        <p class="small muted">You are literally asking the map to show you the parts you
        walked past. Then verify what it says — it's a lead, not a fact.</p>
      </li>
      <li>
        <h4>Push one task until it breaks</h4>
        <p class="muted">Take something it did well and keep escalating: longer, harder,
        more constraints, more data. The point isn't to win — it's to <em>feel</em> where the
        edge is, so you stop guessing. Ten minutes of deliberate breaking teaches more than
        an hour of tutorials.</p>
      </li>
      <li>
        <h4>Watch a competent person work, once</h4>
        <p class="muted">Not a polished tutorial — someone doing their real job with it,
        screen shared, including the bits where it goes wrong. Ninety percent of what you'll
        learn is things you didn't know were possible, not techniques. Ask a colleague. Most
        people are flattered to be asked.</p>
      </li>
      <li>
        <h4>Run the same task in a second model</h4>
        <p class="muted">Once a month, take a real task and give it to a different AI.
        Two things happen: you find out how much of what you assumed was "how AI is" was
        just how <em>that one</em> is, and disagreement between them flags exactly the claims
        worth checking. This doubles as verification — see <a href="trust.html">Trust</a>.</p>
      </li>
    </ol>
  </div>
</section>

<!-- ============================================================ -->
<section id="audit">
  <div class="wrap">
    <p class="slabel">Self-audit</p>
    <h2>Sixteen ordinary things people don't know it can do</h2>
    <p class="lead">
      Tick anything you'd never thought to try. Whatever you leave unticked is your
      map of what you didn't know you didn't know. Saved on this device only.
    </p>

    <div class="card">
      <ul class="checklist">
        <li><input type="checkbox" id="au1"><label for="au1">Paste in a letter from a bank, insurer, or government office and ask what it actually means for me, and what happens if I do nothing.</label></li>
        <li><input type="checkbox" id="au2"><label for="au2">Photograph a fridge shelf and ask for three dinners from what's there.</label></li>
        <li><input type="checkbox" id="au3"><label for="au3">Have it interview me for a job I'm applying to, one hard question at a time.</label></li>
        <li><input type="checkbox" id="au4"><label for="au4">Paste an error message from any app or device and ask what it means in plain words.</label></li>
        <li><input type="checkbox" id="au5"><label for="au5">Ask it to grade my own writing against the job the writing has to do.</label></li>
        <li><input type="checkbox" id="au6"><label for="au6">Turn an hour of meeting notes into decisions, owners, and deadlines.</label></li>
        <li><input type="checkbox" id="au7"><label for="au7">Ask for the strongest case <em>against</em> a decision I've already made.</label></li>
        <li><input type="checkbox" id="au8"><label for="au8">Have it teach me something by quizzing me, not by lecturing me.</label></li>
        <li><input type="checkbox" id="au9"><label for="au9">Rewrite an angry message so it stays firm but lands well.</label></li>
        <li><input type="checkbox" id="au10"><label for="au10">Ask for a spreadsheet formula that does the thing I've been doing by hand.</label></li>
        <li><input type="checkbox" id="au11"><label for="au11">Summarise a long document, then ask what it deliberately left out of the summary.</label></li>
        <li><input type="checkbox" id="au12"><label for="au12">Plan a trip, a party, or a move as a checklist with a running timeline.</label></li>
        <li><input type="checkbox" id="au13"><label for="au13">Ask it to explain something to me three times, each time simpler.</label></li>
        <li><input type="checkbox" id="au14"><label for="au14">Rehearse a difficult conversation, with it playing the other person.</label></li>
        <li><input type="checkbox" id="au15"><label for="au15">Ask which questions I should be asking a doctor, lawyer, or contractor before I meet them.</label></li>
        <li><input type="checkbox" id="au16"><label for="au16">Give it my messy list of anything and ask for it back as a sorted table.</label></li>
      </ul>
      <div class="progress">
        <span data-count>0 of 16</span>
        <span class="bar"><i></i></span>
        <button type="button" class="reset-btn">reset</button>
      </div>
    </div>

    <div class="note note-warn">
      <span class="nlabel">One caveat on that list</span>
      <p>Number 15 is about preparing better questions — not about getting a diagnosis, a
      legal opinion, or a quote. The AI is good at helping you walk in informed. It is not
      the professional, and it does not carry the liability if it's wrong.</p>
    </div>
  </div>
</section>`;
