/* AI Hub — content for tools.html
   The shell (head, nav, hero, pager, footer) is generated by src/layout.js
   from site.config.js. This file is ONLY the body content. */
'use strict';

module.exports = `<div class="wrap">
  <div class="note note-warn">
    <span class="nlabel">Why there are no product names or prices on this page</span>
    <p>Anything specific written here would be wrong within months, and you'd have no way
    to tell which parts had rotted. So this page teaches the shape of the market and how to
    check the current state yourself, which stays true. Written <strong>5 August 2026</strong>.</p>
  </div>
</div>

<!-- ============================================================ -->
<section id="categories">
  <div class="wrap">
    <p class="slabel">The map</p>
    <h2>Six categories. Almost every AI product is one of these.</h2>
    <p class="lead">
      Vendors blur the lines and bundle several into one app. That's fine — you still need
      to know which one you're asking for, because it decides what "good" means.
    </p>

    <div class="acc-tools">
      <button type="button" data-acc="open">Expand all</button>
      <button type="button" data-acc="close">Collapse all</button>
    </div>

    <details class="acc" open>
      <summary><span class="sq">01</span>General chat — the everyday one</summary>
      <div class="acc-body">
        <p>The one most people mean by "AI". Fast, conversational, good at writing,
        explaining, summarising and reformatting. This handles the large majority of
        ordinary use.</p>
        <p class="small muted"><strong>Pick it for:</strong> writing, explaining, drafting,
        tidying, translating, everyday questions.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">02</span>Reasoning — the slow, careful one</summary>
      <div class="acc-body">
        <p>A mode or model that spends noticeably longer before answering, working through
        the problem in steps. Better on multi-step logic, tricky analysis, maths and
        debugging. Slower, and usually more expensive or capped at fewer uses per day.</p>
        <p class="small muted"><strong>Pick it for:</strong> problems where the answer
        depends on getting several steps right in order. Don't use it to reword an email —
        you'll wait longer for no benefit.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">03</span>Search-connected — the one that reads the web now</summary>
      <div class="acc-body">
        <p>Looks things up live and cites what it found, instead of relying only on training
        data. Essential for anything current: prices, news, laws, product comparisons,
        who-currently-holds-what.</p>
        <div class="note note-do"><span class="nlabel">The habit</span>
        <p>Its value is the links. Open them. A search-connected answer you didn't click
        through is no more verified than any other — see <a href="trust.html">Trust</a>.</p></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">04</span>Agents and coding tools — the ones that act</summary>
      <div class="acc-body">
        <p>Take multiple steps without asking each time: search, run code, edit files,
        check their own output, retry. The biggest jump in capability, and the biggest jump
        in what can go wrong unattended.</p>
        <p class="small muted"><strong>Pick it for:</strong> real multi-step work — building
        something, processing many files, anything that would take you an afternoon of
        repetitive steps.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">05</span>Media — images, audio, video, voice</summary>
      <div class="acc-body">
        <p>Generating or editing pictures, transcribing recordings, reading text aloud,
        holding a spoken conversation, producing video. Moving faster than any other
        category, so nothing specific is worth memorising.</p>
        <div class="note note-warn"><span class="nlabel">Two things to know</span>
        <p>Who owns what you generate varies by product and by plan — check before using it
        commercially. And generated people, voices and events can be indistinguishable from
        real ones, which is now your problem as a consumer of media too, not just as a maker.</p></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">06</span>Local / open-weights — the one that runs on your machine</summary>
      <div class="acc-body">
        <p>Models you download and run on your own computer — "open-weights" simply means
        the model file is yours to download. Typically less capable than the best hosted
        ones, but nothing is sent to a company's server, there is no subscription (you pay
        in hardware and electricity instead), and it works offline.</p>
        <p class="small muted"><strong>Pick it for:</strong> genuinely sensitive material,
        or curiosity. Needs a reasonably powerful computer and some patience. Not the place
        to start.</p>
      </div>
    </details>
  </div>
</section>

<!-- ============================================================ -->
<section id="flow">
  <div class="wrap">
    <p class="slabel">The decision</p>
    <h2>Which one, in four questions</h2>

    <ol class="steps">
      <li><h4>Does the answer depend on something recent?</h4>
        <p class="muted">Yes → search-connected, and open the links. No → carry on.</p></li>
      <li><h4>Does it need several steps to be right in sequence?</h4>
        <p class="muted">Yes → the reasoning mode, and expect to wait. No → general chat is
        faster and usually just as good.</p></li>
      <li><h4>Does something need to be <em>done</em>, not just written?</h4>
        <p class="muted">Yes → an agent or coding tool, working on copies, with you reading
        what it did. No → stay in chat.</p></li>
      <li><h4>Is the material genuinely confidential?</h4>
        <p class="muted">Yes → your employer's approved tool, or a local model, or redact
        before pasting. This question overrides all the others.</p></li>
    </ol>

    <div class="note note-info">
      <span class="nlabel">Then pick any serious vendor</span>
      <p>Within a category, the products from the major labs are similar enough that your
      context, your iteration and your checking usually matter more than the choice. Don't
      take that on trust either — it is what your own five-prompt test below is for. Pick
      one, learn it properly, and re-test each quarter. Switching every month costs more
      than it gains.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="free">
  <div class="wrap">
    <p class="slabel">The thing nobody explains</p>
    <h2>"Free until you hit the limit" — what's actually going on</h2>
    <p>
      Free tiers feel like a bait-and-switch. They're not, quite. Every answer costs the
      provider real money in electricity and hardware — unlike ordinary software, where one
      more user costs almost nothing. A free tier is a sample, priced to let you find out
      whether it's worth paying for.
    </p>

    <h3>What that means in practice</h3>
    <ul class="clean">
      <li><strong>Free usually means the smaller or faster model</strong>, or a limited number of the good answers per day. The gap between free and paid is often larger than the gap between two vendors.</li>
      <li><strong>Limits reset on their own schedule</strong>, which varies by product and changes without notice. Your account page is the only current answer.</li>
      <li><strong>The limits move without warning.</strong> Providers change them as capacity and costs change. If a number is written somewhere, treat it as a snapshot.</li>
      <li><strong>Whether your conversations are used for training varies</strong> by product and by plan, and often differs between free and paid. It is a setting in your own account — go and read it.</li>
      <li><strong>"Unlimited" is rarely literally unlimited.</strong> There is almost always an upper bound for unusually heavy use, whether or not it is published.</li>
    </ul>

    <div class="note note-do">
      <span class="nlabel">The honest advice</span>
      <p>If you use it a few times a week, free is genuinely fine — stay there. If you're
      hitting limits mid-task, the interruption is costing you more than the subscription.
      One paid plan, chosen properly and kept for a while, beats juggling three free accounts
      to dodge limits — which mostly teaches you three interfaces and no depth.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="bench">
  <div class="wrap">
    <p class="slabel">The durable skill</p>
    <h2>Build your own five-prompt test</h2>
    <p class="lead">
      Public benchmarks and leaderboards measure things that may have nothing to do with
      your work. The only ranking that matters to you is on your own tasks — and it takes
      about twenty minutes to build a test you can reuse for years.
    </p>

    <ol class="steps">
      <li><h4>Pick five real tasks from your own week</h4>
        <p class="muted">Real ones, with the real material. Cover different shapes: one
        writing, one explaining, one analysing something with numbers, one about your
        specialist subject, one awkward or messy task that has caught tools out before.</p></li>
      <li><h4>Write down what a good answer looks like — before you run it</h4>
        <p class="muted">Do this first or you'll be persuaded by whichever answer is
        best-formatted. One line per task is enough.</p></li>
      <li><h4>Run all five through each candidate, with identical wording</h4>
        <p class="muted">Same text, fresh conversation each time, no follow-ups. Any
        difference in how you asked contaminates the comparison.</p></li>
      <li><h4>Score them yourself, on your own criteria</h4>
        <p class="muted">Right / nearly / wrong is enough. Count the errors on your
        specialist task especially — that's the one where you can actually see the truth.</p></li>
      <li><h4>Keep the five prompts. Re-run them when something new launches.</h4>
        <p class="muted">Now every announcement is a twenty-minute check instead of an
        anxious guess. This is the single most useful thing on this page.</p></li>
    </ol>

    <div class="note note-warn">
      <span class="nlabel">Ignore the number, watch the shape</span>
      <p>Public leaderboards move constantly and often measure exam-style questions. A model
      that tops a chart can still be worse at your actual job than one three places below.
      Your five prompts are worth more than any chart, because they're graded by the only
      person whose opinion decides whether you got value.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="checkyourself">
  <div class="wrap">
    <p class="slabel">Staying current without drowning</p>
    <h2>How to check today's state of play, in five minutes</h2>
    <p>
      Since nothing specific on this page can stay accurate, here's the routine that
      replaces it. Once a quarter is plenty for most people.
    </p>
    <ul class="clean">
      <li><strong>Go to the source, not the commentary.</strong> Each major lab publishes its own model list, limits and pricing. The provider's own documentation is the only thing that is current by definition.</li>
      <li><strong>Read your own account page.</strong> Your plan, your limits and your data-sharing setting are all there, and they're specific to you rather than to an article.</li>
      <li><strong>Use a search-connected AI to summarise the change</strong> — then open the links it gives you. That's the whole point of that category.</li>
      <li><strong>Re-run your five prompts.</strong> Twenty minutes, and it answers the only question you actually had.</li>
      <li><strong>Ignore anything that ranks models without telling you what it tested.</strong> An unexplained ranking is an opinion in a table.</li>
    </ul>

    <div class="note note-info">
      <span class="nlabel">On tutorials, since there are so many</span>
      <p>Judge an AI teacher by five things: do they show a task failing as well as
      succeeding; do they name the model and the date; do they teach checking, not just
      prompting; do they show the boring middle of the work rather than a cut to the result;
      and are they selling a course at the end. Two out of five is usually not worth an hour.</p>
    </div>
  </div>
</section>`;
