/* AI Hub — content for trust.html
   The shell (head, nav, hero, pager, footer) is generated by src/layout.js
   from site.config.js. This file is ONLY the body content. */
'use strict';

module.exports = `<!-- ============================================================ -->
<section id="why">
  <div class="wrap">
    <p class="small" style="margin-bottom:28px">On this page:
      <a href="#triage">how hard to check</a> ·
      <a href="#moves">six checking moves</a> ·
      <a href="#antimoves">what isn't checking</a> ·
      <a href="#tells">failure modes</a> ·
      <a href="#privacy">what never to paste</a> ·
      <a href="#checklist">the checklist</a></p>
    <p class="slabel">Start here</p>
    <h2>The one fact that makes checking non-optional</h2>

    <div class="hero-stat">
      <span class="big">No wobble</span>
      <span class="cap">It sounds exactly the same whether it is right or wrong. There is no hesitation in its voice to warn you.</span>
    </div>

    <figure class="fig" style="margin-top:26px">
      <svg viewBox="0 0 380 150" role="img" aria-label="Diagram: a correct answer and a wrong answer drawn as two speech bubbles with identical steady voice lines">
        <rect x="22" y="30" width="150" height="62" rx="12" fill="var(--surface)" stroke="var(--border-med)" stroke-width="1.2"/>
        <path d="M52 92 L60 106 L70 92" fill="var(--surface)" stroke="var(--border-med)" stroke-width="1.2"/>
        <rect x="208" y="30" width="150" height="62" rx="12" fill="var(--surface)" stroke="var(--border-med)" stroke-width="1.2"/>
        <path d="M238 92 L246 106 L256 92" fill="var(--surface)" stroke="var(--border-med)" stroke-width="1.2"/>
        <path d="M40 61 h22 v-8 h18 v16 h20 v-8 h34" stroke="var(--text-sec)" stroke-width="2" fill="none" stroke-linecap="round"/>
        <path d="M226 61 h22 v-8 h18 v16 h20 v-8 h34" stroke="var(--text-sec)" stroke-width="2" fill="none" stroke-linecap="round"/>
        <text x="97" y="130" text-anchor="middle" font-size="12" fill="var(--green)" font-weight="620">✓ a right answer</text>
        <text x="283" y="130" text-anchor="middle" font-size="12" fill="var(--red)" font-weight="620">✕ an invented one</text>
      </svg>
      <figcaption>The voice is the same line, drawn twice. Nothing in the tone tells you which is which.</figcaption>
    </figure>

    <p>
      A person who is unsure usually sounds unsure. They hedge, they slow down, they say
      "I think". An AI writes a fabricated legal case, a made-up statistic, and a correct
      historical date in exactly the same tone — fluent, calm, well-organised. The signal
      you have used your whole life to gauge reliability simply isn't there.
    </p>
    <p>
      That is not a flaw someone forgot to fix. The system produces text that <em>looks
      like</em> the right answer. When it has the material, looking right and being right
      coincide. When it doesn't, only the first one survives — and it survives at full
      confidence.
    </p>

    <div class="note note-dont">
      <span class="nlabel">The most dangerous case</span>
      <p><strong>Fluent, plausible, and impossible for you to check.</strong> A wrong answer
      you can test is a nuisance — you test it, it fails, you move on. A wrong answer about
      something outside your knowledge, delivered beautifully, goes straight into your work
      and your beliefs and stays there. Whenever you notice you're impressed and unable to
      verify, that's the moment to slow down.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="triage">
  <div class="wrap">
    <p class="slabel">Rule one</p>
    <h2>Match the checking to the cost of being wrong</h2>
    <p class="lead">
      Checking everything is exhausting; checking nothing is how people get hurt. Decide
      by what happens if this is wrong — before you read the answer, not after.
    </p>

    <div class="tscroll">
      <table>
        <thead>
          <tr><th style="width:22%">If it's wrong…</th><th style="width:32%">Examples</th><th>How much to check</th></tr>
        </thead>
        <tbody>
          <tr>
            <td><span class="tag tag-green">Nothing happens</span></td>
            <td>Brainstorming, rewording your own sentence, ideas you'll judge yourself, explaining a concept you'll test in practice anyway.</td>
            <td>Skim it. Your own judgement is the check. Move fast.</td>
          </tr>
          <tr>
            <td><span class="tag tag-amber">You look wrong</span></td>
            <td>A report to your boss, a client email, a statistic you're about to post or repost publicly, code you're about to run, numbers in a deck.</td>
            <td>Check every specific: each number, name, date, quote and claim. Run the code. Assume nothing is right because the rest was.</td>
          </tr>
          <tr>
            <td><span class="tag tag-red">Someone gets hurt</span></td>
            <td>Health, medication, money, legal rights, contracts, safety, tax, anything public, anything you can't undo.</td>
            <td>An independent source or a qualified human. Always. The AI is for preparing your questions, never for the final answer.</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="note note-info">
      <span class="nlabel">Say it out loud before you start</span>
      <p>"If this is wrong, what happens, and who does it happen to?" Ten seconds. It moves
      the decision off how confident you feel and onto what is actually at stake.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="moves">
  <div class="wrap">
    <p class="slabel">Rule two</p>
    <h2>Six verification moves</h2>
    <p class="lead">
      Concrete and mostly fast. Pick by the triage above; make Move 4 automatic.
    </p>

    <div class="acc-tools">
      <button type="button" data-acc="open">Expand all</button>
      <button type="button" data-acc="close">Collapse all</button>
    </div>

    <details class="acc" open>
      <summary><span class="sq">01</span>Ask for sources — then actually open them</summary>
      <div class="acc-body">
        <p>A citation from an AI is a <em>claim that a source exists</em>. It is not evidence.
        Systems that don't genuinely search the web can produce references with a real-sounding
        author, a real-sounding journal, and a title that was never written. Lawyers in
        several countries have been fined or formally reprimanded for filing invented case
        citations — the court checked, and the cases did not exist.</p>
        <p><strong>The move:</strong> ask for the source, then click it. If there's no link,
        search the exact title. If it doesn't exist, discard everything that rested on it —
        and be sceptical of the rest of the answer too.</p>
        <p class="small muted">The common version of this burn: reposting a tidy statistic,
        and three days later someone in the comments asks for the source. There isn't one.</p>
        <div class="note note-do"><span class="nlabel">Two-second tell</span>
        <p>Sources with no links, or links you can't open, are the ones to check first.
        A tool that genuinely searched will normally hand you something clickable.</p></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">02</span>Ask again cold — and in a second model</summary>
      <div class="acc-body">
        <p>Open a brand-new conversation and ask the same question without any of your
        earlier framing. Then ask a different AI product entirely.</p>
        <ul>
          <li><strong>Same answer twice</strong> — mild encouragement, not proof. Two systems trained on overlapping text can be confidently wrong in the same way.</li>
          <li><strong>Different answers</strong> — strong signal. You've just located exactly which claim needs a real source, for about thirty seconds of effort.</li>
        </ul>
        <p class="small muted">The "cold" part matters. Inside the same conversation it is
        anchored on everything already said, including your assumptions. A fresh chat drops that.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">03</span>Make it argue against itself</summary>
      <div class="acc-body">
        <p>Paste the answer back and ask it to attack it. This works far better than asking
        "are you sure?", because you're giving it a different job rather than a chance to
        reassure you.</p>
        <div class="prompt-wrap">
          <button class="copy-btn" type="button">Copy</button>
          <div class="prompt">Here is an answer you gave me. Make the strongest possible case that it is wrong.
List every factual claim in it separately, and for each one say: how could I verify this myself, and how confident should I be?</div>
        </div>
        <p class="small muted">The list of separate claims is the real prize. Prose hides
        how many assertions you were handed; a list makes them countable and checkable.</p>
      </div>
    </details>

    <details class="acc" open>
      <summary><span class="sq">04</span>Check one thing you <em>can</em> check</summary>
      <div class="acc-body">
        <p>The highest value per second on this page. In any answer there is usually
        something verifiable in under a minute: a total that should equal the sum of the
        parts, a date, a name, one link, one line of code.</p>
        <p><strong>Check exactly one.</strong> If it's wrong, stop trusting the whole answer —
        not just that line. Sloppiness in the checkable part is your best available evidence
        about the uncheckable part.</p>
        <div class="note note-do"><span class="nlabel">Make it a reflex</span>
        <p>Never accept a set of numbers without adding them up once yourself. Silent
        arithmetic errors inside a well-formatted table are one of the most common ways
        AI mistakes reach a real audience.</p></div>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">05</span>Prefer questions whose answers can be tested</summary>
      <div class="acc-body">
        <p>You often get to choose the shape of what you ask for. Choose the testable shape.</p>
        <div class="tscroll">
          <table>
            <thead><tr><th>Instead of</th><th>Ask for</th></tr></thead>
            <tbody>
              <tr><td>"Is this contract clause fair?"</td><td>"What does this clause let the other side do that I might not expect? List each one."</td></tr>
              <tr><td>"What's the best way to do X?"</td><td>"Give me three approaches with the trade-off of each, and what would make me pick one over another."</td></tr>
              <tr><td>"Write me a script that does X."</td><td>"Write it, plus a tiny test I can run on sample data to prove it worked."</td></tr>
              <tr><td>"Summarise this."</td><td>"Summarise it, then list what you left out and why."</td></tr>
            </tbody>
          </table>
        </div>
        <p class="small muted">Each right-hand version converts an opinion you'd have to
        trust into a set of statements you can inspect.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">06</span>Calibrate on ground you own</summary>
      <div class="acc-body">
        <p>Ask it about the thing you know best in the world — your job, your hobby, your
        home town, the subject you studied. Read carefully. Count the errors, including the
        subtle ones a non-expert would sail past.</p>
        <p><strong>That number becomes your working assumption</strong> — your rough
        expectation of how often it's wrong — for every topic you <em>can't</em> check.
        Whatever you find, your own figure is worth more than any general claim about AI
        accuracy, including the ones on this page, because you measured it.</p>
        <p class="small muted">Repeat it when you switch tools, and once or twice a year.
        It moves.</p>
      </div>
    </details>
  </div>
</section>

<!-- ============================================================ -->
<section id="antimoves">
  <div class="wrap">
    <p class="slabel">Rule three</p>
    <h2>Four things that feel like checking but aren't</h2>

    <div class="grid grid-2">
      <div class="note note-dont" style="margin:0">
        <span class="nlabel">"Are you sure?"</span>
        <p>Almost useless. Push and it will often apologise and change its answer whether
        or not it was wrong — sometimes replacing a correct answer with a worse one. You
        learn about its agreeableness, not about the fact.</p>
      </div>
      <div class="note note-dont" style="margin:0">
        <span class="nlabel">"How confident are you?"</span>
        <p>It will give you a number, produced the same way the answer was. It is a weak
        hint at best: a low number is worth heeding, a high number proves nothing. Never let
        it stand in for an actual check.</p>
      </div>
      <div class="note note-dont" style="margin:0">
        <span class="nlabel">"I've double-checked this"</span>
        <p>"I verified it" is a sentence, not an event. Re-reading its own answer <em>can</em>
        catch real errors — that is why Move 3 works — but a bare claim to have checked, with
        nothing shown, is not evidence. Look for the working or the tool output, not the
        reassurance.</p>
      </div>
      <div class="note note-dont" style="margin:0">
        <span class="nlabel">It agreed with me</span>
        <p>The weakest signal of all. It leans towards agreeing with the person typing.
        If it confirms what you already believed, you have learned almost nothing —
        that's the moment to go looking for the counter-case.</p>
      </div>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="tells">
  <div class="wrap">
    <p class="slabel">Pattern recognition</p>
    <h2>Eight failure modes, and how each one looks</h2>
    <p class="lead">Learn these by name and you'll start spotting them mid-read.</p>

    <div class="acc-tools">
      <button type="button" data-acc="open">Expand all</button>
      <button type="button" data-acc="close">Collapse all</button>
    </div>

    <details class="acc">
      <summary><span class="sq">01</span>Invented sources</summary>
      <div class="acc-body">
        <p><strong>Looks like:</strong> a confident citation, plausible author, plausible
        journal, no link — or a link that leads to a dead page.</p>
        <p><strong>Catch it:</strong> search the exact title. Thirty seconds.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">02</span>Code that runs and is still wrong</summary>
      <div class="acc-body">
        <p><strong>Looks like:</strong> clean, commented, no errors — and quietly using the
        wrong column, the wrong rounding, or the wrong date range.</p>
        <p><strong>Catch it:</strong> run it on a small example where you already know the
        right answer by hand. "No error message" is not "correct".</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">03</span>Stale facts stated in the present tense</summary>
      <div class="acc-body">
        <p><strong>Looks like:</strong> current-sounding claims about prices, laws, versions,
        people's jobs, or which product is best — frozen at the training cutoff.</p>
        <p><strong>Catch it:</strong> for anything time-sensitive, ask when its information
        is from, and check it against a live source yourself.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">04</span>Sycophancy</summary>
      <div class="acc-body">
        <p><strong>Looks like:</strong> "Great question!", enthusiastic agreement with your
        framing, a plan that has no downsides.</p>
        <p><strong>Catch it:</strong> ask for the case against. If the case against is thin,
        ask again more forcefully — a real analysis has real costs in it.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">05</span>Anchoring on your framing</summary>
      <div class="acc-body">
        <p><strong>Looks like:</strong> you asked "why is X better than Y?" and got a fluent
        essay on why X is better — because you asked for it, not because it is.</p>
        <p><strong>Catch it:</strong> ask neutrally in a fresh chat: "Compare X and Y. Which
        is better for this situation, and why might I be wrong to prefer either?"</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">06</span>Confident middles, invented edges</summary>
      <div class="acc-body">
        <p><strong>Looks like:</strong> the general explanation is solid; the specific
        figure, exact quote, precise date or edge case is fabricated.</p>
        <p><strong>Catch it:</strong> trust the shape, check the specifics. Precision is
        where invention hides — an oddly exact number with no source is a flag, not a
        credential.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">07</span>Silent unit, currency and scale errors</summary>
      <div class="acc-body">
        <p><strong>Looks like:</strong> a mix of millions and billions, dollars and pounds,
        percent and percentage points, metric and imperial — all inside one tidy table.</p>
        <p><strong>Catch it:</strong> check that the units are stated, consistent, and that
        the totals add up. This one reaches real audiences constantly because the formatting
        looks so authoritative.</p>
      </div>
    </details>

    <details class="acc">
      <summary><span class="sq">08</span>Over-generalising from your one example</summary>
      <div class="acc-body">
        <p><strong>Looks like:</strong> you gave it one sample row, one file, or one case,
        and it produced something that only works for that one and breaks on the rest.</p>
        <p><strong>Catch it:</strong> test on the awkward cases — the empty one, the
        duplicate, the one with a missing field, the one in a different format.</p>
      </div>
    </details>
  </div>
</section>

<!-- ============================================================ -->
<section id="privacy">
  <div class="wrap">
    <p class="slabel">The other half of trust</p>
    <h2>Trusting it with your information is a separate decision</h2>
    <p>
      Everything above is about trusting what comes <em>out</em>. This is about what goes
      <em>in</em> — a different question, with a different answer, and one people get wrong
      more casually.
    </p>

    <div class="grid grid-2">
      <div class="card">
        <h3>Never paste</h3>
        <ul class="clean no small" style="margin-top:8px">
          <li>Passwords, keys, one-time codes, card numbers</li>
          <li>Other people's personal or medical details</li>
          <li>Customer data, or anything under a confidentiality agreement</li>
          <li>Unreleased financials or anything price-sensitive</li>
          <li>Anything you'd be uncomfortable seeing quoted back at you</li>
        </ul>
      </div>
      <div class="card">
        <h3>Check before you rely on it</h3>
        <ul class="clean small" style="margin-top:8px">
          <li>Whether your conversations may be used to train the model — it varies by product and by plan, and the setting can move</li>
          <li>Whether your employer has an approved tool, and whether the free consumer version is allowed</li>
          <li>Whether the account is personal or company-issued — that usually decides who can read it</li>
          <li>The provider's data settings page, in your own account, today</li>
        </ul>
      </div>
    </div>

    <div class="note note-warn">
      <span class="nlabel">A simple test that works</span>
      <p>Before pasting, ask: <strong>would I be comfortable if this text appeared in a
      screenshot in a news story next year?</strong> If not, don't paste it. Removing names
      and numbers helps, but it does not make a document safe — a paragraph can still
      identify someone from context, and a redacted contract is still under the
      confidentiality agreement. When it genuinely matters, use the tool your employer has
      approved, or don't use one. Asking takes a minute. A leaked document can cost a career.</p>
    </div>
  </div>
</section>

<!-- ============================================================ -->
<section id="checklist">
  <div class="wrap">
    <p class="slabel">Keep this</p>
    <h2>The one-page check</h2>
    <p class="lead">
      Run this on anything that leaves your desk. It takes about two minutes once it's
      a habit. Ticks are saved on this device.
    </p>

    <div class="card">
      <ul class="checklist">
        <li><input type="checkbox" id="ck1"><label for="ck1"><strong>Stakes.</strong> I said out loud what happens if this is wrong, and who it happens to.</label></li>
        <li><input type="checkbox" id="ck2"><label for="ck2"><strong>Specifics.</strong> Every number, name, date and quote has been checked — not just the ones that looked odd.</label></li>
        <li><input type="checkbox" id="ck3"><label for="ck3"><strong>Arithmetic.</strong> I added up the totals myself. They add up.</label></li>
        <li><input type="checkbox" id="ck4"><label for="ck4"><strong>Sources.</strong> I opened them. They exist and they say what the answer claims.</label></li>
        <li><input type="checkbox" id="ck5"><label for="ck5"><strong>Freshness.</strong> Nothing here depends on facts that could have changed since its training cutoff.</label></li>
        <li><input type="checkbox" id="ck6"><label for="ck6"><strong>Counter-case.</strong> I asked for the strongest argument against, and read it properly.</label></li>
        <li><input type="checkbox" id="ck7"><label for="ck7"><strong>Test.</strong> Any code, formula or calculation was run on an example whose answer I already knew.</label></li>
        <li><input type="checkbox" id="ck8"><label for="ck8"><strong>Edges.</strong> I tried the awkward cases, not just the clean one.</label></li>
        <li><input type="checkbox" id="ck9"><label for="ck9"><strong>Privacy.</strong> Nothing confidential went in, and I know where this conversation is stored.</label></li>
        <li><input type="checkbox" id="ck10"><label for="ck10"><strong>Ownership.</strong> I can explain and defend every line of this without saying "the AI wrote it."</label></li>
      </ul>
      <div class="progress">
        <span data-count>0 of 10</span>
        <span class="bar"><i></i></span>
        <button type="button" class="reset-btn">reset</button>
      </div>
    </div>

    <div class="note note-do">
      <span class="nlabel">The last one is the whole track in a sentence</span>
      <p>The moment it goes out with your name on it, it is your work and your mistake.
      "The AI said so" has not saved anyone yet, and it is not something to plan around.
      That isn't a reason to avoid the tool — it's the reason to check it.</p>
    </div>
  </div>
</section>`;
